# Generated by Django 3.1.3 on 2020-12-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
    ]
