# Generated by Django 2.2.5 on 2019-09-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='university',
            new_name='address3',
        ),
    ]
