# Generated by Django 2.2.1 on 2019-09-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190917_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr'), ('MS', 'Ms'), ('MRS', 'Mrs'), ('DR', 'Dr')], default='MR', max_length=3),
            preserve_default=False,
        ),
    ]
