exclude: "^docs/|/migrations/|^tests/"
default_stages: [pre-commit]

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      # - id: check-added-large-files
        # args: [--maxkb=100]
      - id: check-merge-conflict
      - id: check-json
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: fix-byte-order-marker
      - id: check-ast
      - id: check-toml
      # - id: check-vcs-permalinks

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.9.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  # - repo: https://github.com/python-poetry/poetry
  #   rev: '1.5.1'
  #   hooks:
  #     - id: poetry-check
  #     - id: poetry-lock
  #     - id: poetry-export
  #       args: ["-o", "requirements.txt", "--with=dev", "--without-hashes"]


# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
