# Generated by Django 4.2.1 on 2023-05-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ghfdb", "0002_remove_interval_historic_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interval",
            options={
                "default_related_name": "intervals",
                "ordering": ["relevant_child", "q_top"],
                "verbose_name": "Interval",
                "verbose_name_plural": "Heat Flow (Child)",
            },
        ),
        migrations.RemoveField(
            model_name="interval",
            name="reference",
        ),
        migrations.RemoveField(
            model_name="interval",
            name="site",
        ),
        migrations.AddField(
            model_name="interval",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="parent heat flow site",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervals",
                to="ghfdb.heatflow",
                verbose_name="parent",
            ),
        ),
    ]
