# Generated by Django 5.2.5 on 2026-04-10 16:03

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ghfdb", "0001_initial"),
        ("heat_flow", "0009_heatflow_local_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GHFDB",
            fields=[],
            options={
                "verbose_name": "GHFDB Entry",
                "verbose_name_plural": "GHFDB Entries",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("heat_flow.heatflow",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
