# Generated by Django 5.2.5 on 2026-04-10 16:03

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ghfdb", "0001_initial"),
        # The proxy needs HeatFlow to exist and nothing more. This pointed at
        # 0009 because that was the latest migration when it was generated; 0011
        # has since reversed 0009's only effect.
        ("heat_flow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GHFDB",
            fields=[],
            options={
                "verbose_name": "GHFDB Child",
                "verbose_name_plural": "GHFDB Children",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("heat_flow.heatflow",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
