#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export PYTHONPATH=../geoluminate:../geoluminate-earth-science:../django-literature:../django-ror:../django-controlled-vocabulary:../django-laboratory

python manage.py migrate
python manage.py compress

exec python manage.py runserver_plus 0.0.0.0:8000

