# Generated by Django 3.0.4 on 2020-03-31 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='co_authors',
            field=models.ManyToManyField(blank=True, related_name='as_coauthor', to='reference.Author'),
        ),
        migrations.AddField(
            model_name='reference',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reference',
            name='first_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='as_first_author', to='reference.Author'),
        ),
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('first_author', 'year', 'bib_id')},
        ),
    ]
