# Generated by Django 2.2.1 on 2019-07-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_filestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='date_added',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='filestorage',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
