# Generated by Django 2.2.1 on 2019-07-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_auto_20190716_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestorage',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
