# Generated by Django 2.2.5 on 2019-09-17 09:35

from django.db import migrations, models
import reference.models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_filestorage_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='data',
            field=models.FileField(upload_to=reference.models.file_storage_path),
        ),
    ]
