# Generated by Django 2.2.1 on 2019-10-02 01:26

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_filestorage_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('year'), descending=True, nulls_last=True)]},
        ),
        migrations.AddField(
            model_name='reference',
            name='bibtex',
            field=models.TextField(blank=True),
        ),
    ]
