# Generated by Django 2.2.1 on 2019-10-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_auto_20191002_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='journal',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
