# Generated by Django 2.2.1 on 2019-10-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0011_reference_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='source',
        ),
    ]
