# Generated by Django 3.2.15 on 2022-08-29 13:29

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('link', models.URLField(verbose_name='link')),
                ('snippet', django_ckeditor_5.fields.CKEditor5Field(verbose_name='html snippet')),
            ],
        ),
    ]
