# Generated by Django 3.2.15 on 2022-08-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gfz_dataservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Licenses',
            new_name='License',
        ),
    ]
