# Generated by Django 3.2.15 on 2022-08-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfz_dataservices', '0002_rename_licenses_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('provided_id', models.CharField(max_length=128, verbose_name='provided ID')),
                ('keyword', models.CharField(max_length=128, verbose_name='keyword')),
                ('help', models.TextField(verbose_name='additional information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='license',
            name='link',
        ),
        migrations.AddField(
            model_name='license',
            name='about',
            field=models.TextField(default='', verbose_name='about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='url',
            field=models.URLField(default='', verbose_name='url'),
            preserve_default=False,
        ),
    ]
