# Generated by Django 3.2.15 on 2022-08-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfz_dataservices', '0003_auto_20220829_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='name',
            field=models.CharField(default='', max_length=128, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyword',
            name='help',
            field=models.TextField(blank=True, null=True, verbose_name='additional information'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='keyword',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='keyword'),
        ),
    ]
