# Generated by Django 3.2.15 on 2022-08-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfz_dataservices', '0004_auto_20220829_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='url',
        ),
        migrations.AlterField(
            model_name='license',
            name='snippet',
            field=models.TextField(verbose_name='html snippet'),
        ),
    ]
