# Generated by Django 3.2.15 on 2022-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfz_dataservices', '0007_alter_schema_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schema',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='schema',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
