# Generated by Django 3.0.4 on 2020-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'basin',
            },
        ),
        migrations.CreateModel(
            name='CrustalThickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'db_table': 'crustal_thickness',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_size', models.FloatField(blank=True, null=True)),
                ('dominant_mineral_phase', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('fabric', models.CharField(blank=True, max_length=50)),
                ('texture', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'sample_description',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'formation',
            },
        ),
        migrations.CreateModel(
            name='GeologicalProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'geological_province',
            },
        ),
        migrations.CreateModel(
            name='GeologicalUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'geological_unit',
            },
        ),
        migrations.CreateModel(
            name='OutcropDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'db_table': 'outcrop_distance',
            },
        ),
        migrations.CreateModel(
            name='SedimentThickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='value')),
            ],
            options={
                'db_table': 'sediment_thickness',
            },
        ),
        migrations.CreateModel(
            name='TectonicEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'tectonic_environment',
            },
        ),
    ]
