# Generated by Django 2.2.1 on 2019-07-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basin', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'geological_basin',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grain_size', models.FloatField(blank=True, null=True)),
                ('dominant_mineral_phase', models.CharField(blank=True, max_length=50)),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('fabric', models.CharField(blank=True, max_length=50)),
                ('texture', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'sample_description',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'geological_domain',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'geological_formation',
            },
        ),
        migrations.CreateModel(
            name='Lithology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lithology', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'lithology',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'geological_province',
            },
        ),
        migrations.CreateModel(
            name='TectonicEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tectonic_environment', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tectonic_environment',
            },
        ),
    ]
