# Generated by Django 3.0.4 on 2020-03-31 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geomodels', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedimentthickness',
            name='reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reference.Reference', verbose_name='reference'),
        ),
    ]
