# Generated by Django 5.1.3 on 2025-01-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentheatflow',
            name='sample2',
            field=models.ForeignKey(blank=True, help_text='The sample on which the measurement was made.', null=True, on_delete=django.db.models.deletion.PROTECT, to='heat_flow.heatflowsite', verbose_name='sample'),
        ),
        migrations.DeleteModel(
            name='GHFDBDataset',
        ),
    ]
