# Generated by Django 3.2.15 on 2022-09-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_site_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interval',
            options={'default_related_name': 'intervals', 'ordering': ['site', 'childcomp', 'q_top'], 'verbose_name': 'Heat Flow', 'verbose_name_plural': 'Heat Flow'},
        ),
    ]
