# Generated by Django 3.1.3 on 2021-07-07 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('editorial', '0002_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='image_placement',
            field=models.CharField(choices=[('top', 'Top'), ('left', 'Left'), ('right', 'Right')], default='r', max_length=5, null=True),
        ),
    ]
