# Generated by Django 3.1.3 on 2021-07-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('editorial', '0005_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeading',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='editorial_pageheading', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(max_length=128)),
                ('sub_title', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
