# Generated by Django 2.2.1 on 2019-07-05 04:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductivity',
            fields=[
                ('sample_name', models.CharField(blank=True, max_length=200)),
                ('value', models.FloatField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=200)),
                ('number_of_measurements', models.IntegerField(default=1)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('rock_group', models.CharField(blank=True, choices=[('metamorphic', 'Metamorphic'), ('igneous', 'Igneous'), ('sedimentary', 'Sedimentary'), ('metaigneous', 'Meta-Igneous'), ('metasedimentary', 'Meta-Sedimentary')], max_length=15)),
                ('rock_origin', models.CharField(blank=True, choices=[('plutonic', 'Plutonic'), ('volcanic', 'Volcanic')], max_length=8)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('age_min', models.FloatField(blank=True, null=True)),
                ('age_max', models.FloatField(blank=True, null=True)),
                ('age_method', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'conductivity',
                'db_table': 'thermal_conductivity',
            },
        ),
        migrations.CreateModel(
            name='DepthInterval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('age_min', models.FloatField(blank=True, null=True)),
                ('age_max', models.FloatField(blank=True, null=True)),
                ('age_method', models.CharField(blank=True, max_length=200)),
                ('depth_min', models.FloatField(blank=True, null=True)),
                ('depth_max', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'depth_interval',
            },
        ),
        migrations.CreateModel(
            name='HeatFlow',
            fields=[
                ('corrected', models.FloatField(blank=True, null=True)),
                ('corrected_uncertainty', models.FloatField(blank=True, null=True)),
                ('uncorrected', models.FloatField(blank=True, null=True)),
                ('uncorrected_uncertainty', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('reliability', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('R', 'R'), ('Z', 'Z')], max_length=1, null=True)),
            ],
            options={
                'verbose_name_plural': 'heat flow',
                'db_table': 'heat_flow',
            },
        ),
        migrations.CreateModel(
            name='HeatFlowCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'heat_flow_correction',
            },
        ),
        migrations.CreateModel(
            name='HeatGeneration',
            fields=[
                ('sample_name', models.CharField(blank=True, max_length=200)),
                ('value', models.FloatField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=200)),
                ('number_of_measurements', models.IntegerField(default=1)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('rock_group', models.CharField(blank=True, choices=[('metamorphic', 'Metamorphic'), ('igneous', 'Igneous'), ('sedimentary', 'Sedimentary'), ('metaigneous', 'Meta-Igneous'), ('metasedimentary', 'Meta-Sedimentary')], max_length=15)),
                ('rock_origin', models.CharField(blank=True, choices=[('plutonic', 'Plutonic'), ('volcanic', 'Volcanic')], max_length=8)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('age_min', models.FloatField(blank=True, null=True)),
                ('age_max', models.FloatField(blank=True, null=True)),
                ('age_method', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'heat generation',
                'db_table': 'heat_generation',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('well_depth', models.FloatField(blank=True, null=True)),
                ('dip', models.FloatField(blank=True, null=True)),
                ('operator', models.CharField(blank=True, max_length=150, null=True)),
                ('cruise', models.CharField(blank=True, max_length=150, null=True)),
                ('sediment_thickness', models.FloatField(blank=True, null=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['site_name'])),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('sample_name', models.CharField(blank=True, max_length=200)),
                ('value', models.FloatField()),
                ('uncertainty', models.FloatField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=200)),
                ('number_of_measurements', models.IntegerField(default=1)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('rock_group', models.CharField(blank=True, choices=[('metamorphic', 'Metamorphic'), ('igneous', 'Igneous'), ('sedimentary', 'Sedimentary'), ('metaigneous', 'Meta-Igneous'), ('metasedimentary', 'Meta-Sedimentary')], max_length=15)),
                ('rock_origin', models.CharField(blank=True, choices=[('plutonic', 'Plutonic'), ('volcanic', 'Volcanic')], max_length=8)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('age_min', models.FloatField(blank=True, null=True)),
                ('age_max', models.FloatField(blank=True, null=True)),
                ('age_method', models.CharField(blank=True, max_length=200)),
                ('lag_time', models.FloatField(blank=True, null=True)),
                ('is_top_of_hole', models.BooleanField(default=False)),
                ('is_bottom_of_hole', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'temperature',
                'db_table': 'temperature',
            },
        ),
        migrations.CreateModel(
            name='TemperatureGradient',
            fields=[
                ('corrected', models.FloatField(blank=True, null=True)),
                ('corrected_uncertainty', models.FloatField(blank=True, null=True)),
                ('uncorrected', models.FloatField(blank=True, null=True)),
                ('uncorrected_uncertainty', models.FloatField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.CharField(blank=True, max_length=150, null=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('depth_interval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DepthInterval')),
            ],
            options={
                'db_table': 'temperature_gradient',
            },
        ),
    ]
