# Generated by Django 3.1 on 2020-09-11 04:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='This is how the field should appear in any download files.', max_length=100, verbose_name='field name')),
                ('answer', ckeditor.fields.RichTextField(help_text='A description of the field', verbose_name='field description')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'FAQ',
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='This is how the field should appear in any download files.', max_length=100, verbose_name='field name')),
                ('description', ckeditor.fields.RichTextField(help_text='A description of the field', verbose_name='field description')),
                ('units', models.CharField(blank=True, help_text='Default unit of measurement', max_length=15, null=True, verbose_name='units')),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='The headline display for this news.', max_length=150, verbose_name='headline')),
                ('content', ckeditor.fields.RichTextField(help_text='A description of the field', verbose_name='content')),
                ('published', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'news',
                'db_table': 'news',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='The heading on the page.', max_length=150, verbose_name='heading')),
                ('sub_heading', models.CharField(blank=True, help_text='Appears as a sub heading under the main heading. Slightly smaller font.', max_length=250, null=True, verbose_name='sub heading')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Page content that appears underneath the headings.', null=True, verbose_name='content')),
                ('title', models.CharField(blank=True, help_text='Appears in the browser tab before "| HeatFlow.org". If blank, heading will be used instead.', max_length=50, null=True, verbose_name='title')),
                ('keywords', models.CharField(help_text='Keywords to include in the page <head> tags', max_length=250, verbose_name='keywords')),
                ('description', ckeditor.fields.RichTextField(blank=True, help_text='Description to include in the page <head> tags', null=True, verbose_name='decsription')),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
