# Generated by Django 3.0.4 on 2020-03-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='This is how the field should appear in any download files.', max_length=100, verbose_name='field name')),
                ('description', models.TextField(help_text='A description of the field', verbose_name='field description')),
                ('units', models.CharField(blank=True, help_text='Default unit of measurement', max_length=15, null=True, verbose_name='units')),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['field_name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Appears in the browser tab before "| HeatFlow.org". If blank, heading will be used instead.', max_length=50, null=True, verbose_name='title')),
                ('heading', models.CharField(help_text='The heading on the page.', max_length=150, verbose_name='heading')),
                ('sub_heading', models.CharField(blank=True, help_text='Appears as a sub heading under the main heading. Slightly smaller font.', max_length=250, null=True, verbose_name='sub heading')),
                ('content', models.TextField(blank=True, help_text='Page content that appears underneath the headings.', null=True, verbose_name='content')),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
