# Generated by Django 2.2.1 on 2019-07-05 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('geomodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturegradient',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temperature',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Description'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='temperature',
            name='lithology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Lithology'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Reference'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.AddField(
            model_name='site',
            name='basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basin_name', to='geomodels.Basin'),
        ),
        migrations.AddField(
            model_name='site',
            name='bottom_hole_temp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_hole_temp', to='main.Temperature'),
        ),
        migrations.AddField(
            model_name='site',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Domain'),
        ),
        migrations.AddField(
            model_name='site',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='site',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Province'),
        ),
        migrations.AddField(
            model_name='site',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Reference'),
        ),
        migrations.AddField(
            model_name='site',
            name='sub_basin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_basin_name', to='geomodels.Basin'),
        ),
        migrations.AddField(
            model_name='site',
            name='tectonic_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.TectonicEnvironment'),
        ),
        migrations.AddField(
            model_name='site',
            name='top_hole_temp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_hole_temp', to='main.Temperature'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='depth_interval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DepthInterval'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Description'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='lithology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Lithology'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Reference'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='corrections',
            field=models.ManyToManyField(blank=True, to='main.HeatFlowCorrection'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='depth_interval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DepthInterval'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depthinterval',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depthinterval',
            name='lithology',
            field=models.ManyToManyField(blank=True, to='geomodels.Lithology'),
        ),
        migrations.AddField(
            model_name='depthinterval',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Reference'),
        ),
        migrations.AddField(
            model_name='depthinterval',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='depth_interval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.DepthInterval'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Description'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='edited_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='lithology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geomodels.Lithology'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Reference'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('value', 'depth', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('site_name', 'latitude', 'longitude', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='heatgeneration',
            unique_together={('value', 'depth', 'site')},
        ),
        migrations.AlterUniqueTogether(
            name='conductivity',
            unique_together={('value', 'depth', 'site')},
        ),
    ]
