# Generated by Django 3.1.3 on 2020-11-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200925_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, help_text='Description to include in the page <head> tags', null=True, verbose_name='decsription'),
        ),
    ]
