# Generated by Django 2.2.1 on 2019-07-05 09:17

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190705_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['latitude', 'longitude']),
        ),
    ]
