# Generated by Django 3.1.3 on 2020-12-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201124_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='verbose_field_name',
            field=models.CharField(default='', help_text='A verbose version of the field name', max_length=128, verbose_name='verbose field name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(help_text='This is how the field should appear in any download files.', max_length=128, verbose_name='field name'),
        ),
        migrations.AlterField(
            model_name='field',
            name='units',
            field=models.CharField(blank=True, help_text='Standard unit of measurement', max_length=32, null=True, verbose_name='units'),
        ),
    ]
