# Generated by Django 3.1.3 on 2020-12-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201203_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='table',
            field=models.CharField(choices=[('S', 'Site'), ('I', 'Interval'), ('C', 'Corrections'), ('T', 'Temperature'), ('TC', 'Thermal Conductivity'), ('HG', 'Heat Generation')], default='S', help_text='the database table to which this measurement belongs', max_length=2, verbose_name='database table'),
            preserve_default=False,
        ),
    ]
