# Generated by Django 2.2.1 on 2019-10-02 01:26

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190705_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('site_name'), descending=True, nulls_last=True)]},
        ),
    ]
