# Generated by Django 3.1.3 on 2020-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_field_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='table',
            field=models.CharField(choices=[('S', 'Site'), ('I', 'Interval'), ('C', 'Corrections'), ('T', 'Temperature'), ('TC', 'Thermal Conductivity'), ('HG', 'Heat Generation')], help_text='The database table to which this measurement belongs', max_length=2, verbose_name='database table'),
        ),
    ]
