# Generated by Django 3.1.3 on 2020-12-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201203_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='download_only',
            field=models.BooleanField(default=False, help_text='This should be set to true if it is avaliable but users cannot supply data for it. Reserverd for fields calculated by the application.', verbose_name='download only'),
        ),
        migrations.AddField(
            model_name='field',
            name='required',
            field=models.BooleanField(default=False, help_text='Is the field required during upload of data into this table', verbose_name='required field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_name',
            field=models.CharField(help_text='This is how the field should appear in any download files.', max_length=128, verbose_name='DB field name'),
        ),
        migrations.AlterField(
            model_name='field',
            name='verbose_field_name',
            field=models.CharField(help_text='A verbose version of the field name', max_length=128, verbose_name='field'),
        ),
    ]
