# Generated by Django 3.1.3 on 2020-12-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201203_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['table', '-required', 'download_only', 'field_name']},
        ),
        migrations.AlterField(
            model_name='field',
            name='units',
            field=models.CharField(blank=True, help_text='Standard unit of measurement. Please write these in mathjax format for proper display on the web. basic syntax is \\( latex math notation \\).', max_length=32, null=True, verbose_name='units'),
        ),
    ]
