# Generated by Django 3.1.3 on 2020-12-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201204_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['-table', '-required', 'download_only', 'field_name']},
        ),
        migrations.AlterField(
            model_name='field',
            name='units',
            field=models.CharField(blank=True, help_text='Standard unit of measurement. Can be written in LaTex format by surrounding units with \\\\( latex here \\\\).', max_length=32, null=True, verbose_name='units'),
        ),
    ]
