# Generated by Django 3.2.15 on 2022-08-09 15:08

import core.fields
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import meta.models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('database', '0027_auto_20220809_1708'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0009_alter_publication_abstract'),
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', length=10, max_length=15, prefix='GHFS-', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Specification of the (local) name of the related heat-flow site or the related survey.', max_length=255, null=True, verbose_name='name')),
                ('lat', models.DecimalField(db_index=True, decimal_places=5, help_text='Latitude in decimal degrees', max_digits=7, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)], verbose_name='latitude')),
                ('lng', models.DecimalField(db_index=True, decimal_places=5, help_text='Longitude in decimal degrees', max_digits=8, validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='longitude')),
                ('elevation', core.fields.RangeField(blank=True, help_text='site elevation with reference to mean sea level (m)', null=True, validators=[django.core.validators.MaxValueValidator(9000), django.core.validators.MinValueValidator(-12000)], verbose_name='elevation (m)')),
                ('q', models.FloatField(help_text='site heat flow value', verbose_name='heat flow')),
                ('q_unc', core.fields.RangeField(blank=True, help_text='uncertainty standard deviation of the reported heat-flow value as estimated by an error propagation from uncertainty in thermal conductivity and temperature gradient (corrected preferred over measured gradient).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='heat flow uncertainty')),
                ('q_acq', models.DateField(help_text='Year of acquisition of the heat-flow data in the form "YYYY-MM" (may differ from publication year)', null=True, verbose_name='date acquired')),
                ('env', models.CharField(choices=[('onshore (continental)', 'Onshore (Continental)'), ('onshore (lake)', 'Onshore (Lake)'), ('offshore (continental)', 'Offshore (Continental)'), ('offshore (marine)', 'Offshore (Marine)'), ('unspecified', 'Unspecified')], default='unspecified', help_text='Describes the general geographical setting of the heat-flow site (not the applied methodology).', max_length=22, verbose_name='basic geographical environment')),
                ('wat_temp', models.FloatField(blank=True, help_text='Seafloor temperature where heat-flow measurements were taken.', null=True, verbose_name='bottom water temperature (°C)')),
                ('method', models.CharField(blank=True, choices=[('drilling', 'Drilling'), ('mining', 'Mining'), ('tunneling', 'Tunneling'), ('probing (lake)', 'Probing (Lake)'), ('probing (ocean)', 'Probing (Ocean)'), ('unspecified', 'Unspecified')], help_text='Specification of the general means by which the rock was accessed by temperature sensors for the respective data entry.', max_length=15, null=True, verbose_name='exploration method')),
                ('expl', models.CharField(blank=True, choices=[('hydrocarbon', 'Hydrocarbon'), ('underground storage', 'Underground Storage'), ('geothermal', 'Geothermal'), ('mapping', 'Mapping'), ('mining', 'Mining'), ('tunneling', 'Tunneling'), ('unspecified', 'Unspecified')], help_text='Main purpose of the original excavation providing access for the temperature sensors.', max_length=19, null=True, verbose_name='exploration purpose')),
                ('q_comment', models.TextField(blank=True, help_text='General comments regarding the heat flow site/measurement', null=True, verbose_name='general comments')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('continent', models.ForeignKey(blank=True, help_text='Continent land boundaries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='mapping.continent', verbose_name='continent')),
                ('country', models.ForeignKey(blank=True, help_text='Country land boundaries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='mapping.country', verbose_name='country')),
                ('ocean', models.ForeignKey(blank=True, help_text='Global oceans and seas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='mapping.ocean', verbose_name='ocean')),
                ('plate', models.ForeignKey(blank=True, help_text='tectonic plate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='mapping.plate', verbose_name='plate')),
                ('political', models.ForeignKey(blank=True, help_text='Countries inclusive of exclusive marine economic zones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='mapping.political', verbose_name='political region')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='mapping.province', verbose_name='geological province')),
                ('references', models.ManyToManyField(blank=True, help_text='The reference or publication from which the data were sourced. Each site may have multiple references.', related_name='review_sites', to='publications.Publication', verbose_name='references')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'db_table': 'site_review',
                'ordering': ['-date_added'],
                'abstract': False,
                'default_related_name': 'review_sites',
                'unique_together': {('name', 'lat', 'lng')},
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominated', models.DateTimeField(auto_now=True, help_text='Date the user nominated themselves to review this publication', verbose_name='reviewer nominated')),
                ('accepted', models.DateTimeField(auto_now=True, help_text='Date the review was accepted by site admins and incorporated into the production database', verbose_name='review accepted')),
                ('submitted', models.DateTimeField(blank=True, help_text='Date the user submitted correction for final approval by site admins', null=True, verbose_name='review submitted')),
                ('publication', models.OneToOneField(help_text='Publication being review', null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.publication')),
                ('reviewer', models.OneToOneField(help_text='User reviewing this publication', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', length=8, max_length=15, prefix='GHFI-', primary_key=True, serialize=False)),
                ('historic_id', models.PositiveIntegerField(blank=True, help_text='This is the numeric identifier used in old forms of the GHFDB to identify measurements', null=True, verbose_name='Historic ID')),
                ('qc', models.FloatField(help_text='heat flow value', verbose_name='heat flow')),
                ('qc_unc', core.fields.RangeField(blank=True, help_text='uncertainty standard deviation of the reported heat-flow value as estimated by an error propagation from uncertainty in thermal conductivity and temperature gradient (corrected preferred over measured gradient).', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='uncertainty')),
                ('q_method', models.CharField(blank=True, choices=[('fourier', "Fourier's Law"), ('product', 'Product method'), ('interval', 'Interval method'), ('bullard', 'Bullard'), ('bootsrap', 'Bootstrap')], help_text='Principal method of heat-flow density calculation from temperature and thermal conductivity data', max_length=8, null=True, verbose_name='method')),
                ('q_top', core.fields.RangeField(blank=True, help_text='Describes the true vertical depth of the top end of the heat-flow determination interval relative to the land surface/ocean bottom.', null=True, validators=[django.core.validators.MaxValueValidator(12500)], verbose_name='interval top (m)')),
                ('q_bot', core.fields.RangeField(blank=True, help_text='Describes the true vertical depth of the bottom end of the heat-flow determination interval relative to the land surface/ocean bottom.', null=True, validators=[django.core.validators.MaxValueValidator(12500), django.core.validators.MinValueValidator(0)], verbose_name='interval bottom (m)')),
                ('hf_pen', core.fields.RangeField(blank=True, help_text='Depth of penetration of marine probe into the sediment.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='penetration depth (m)')),
                ('hf_probe', models.CharField(blank=True, choices=[('corer-outrigger', 'Corer-outrigger'), ('bullard', 'Bullard Probe'), ('lister/violin', 'Lister Violin-Bow Probe'), ('ewing', 'Ewing Probe'), ('other', 'Other'), ('unspecified', 'Unspecified')], help_text='Type of marine probe used for measurement.', max_length=15, null=True, verbose_name='probe type')),
                ('hf_probeL', core.fields.RangeField(blank=True, help_text='length of the marine probe.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='probe length (m)')),
                ('T_tilt', core.fields.RangeField(blank=True, help_text='Tilt of the marine probe.', null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(0)], verbose_name='tilt (deg)')),
                ('q_tf_mech', models.CharField(blank=True, choices=[('conductive', 'Conductive'), ('convective unspecified', 'Convective - unspecified'), ('convective upflow', 'Convective - upflow'), ('convective downflow', 'Convective - downflow'), ('unspecified', 'Unspecified')], help_text='Specification of the predominant heat transfer mechanism relevant to the reported heat flow value.', max_length=22, null=True, verbose_name='transfer mechanism')),
                ('q_acq', models.DateField(blank=True, help_text='Year of acquisition of the heat-flow data (may differ from publication year)', null=True, verbose_name='date of acquisition (YYYY-MM)')),
                ('childcomp', models.BooleanField(blank=True, default=None, help_text='Specifies whether the child entry is used for computation of representative location heat flow values at the parent level or not.', null=True, verbose_name='Is relevant child?')),
                ('geo_lith', models.CharField(blank=True, help_text='Dominant rock type/lithology within the interval of heat-flow determination. Use existing BGS rock classification scheme for naming the lithology.', max_length=255, null=True, verbose_name='lithology')),
                ('geo_strat', models.CharField(blank=True, help_text='Stratigraphic age of the depth range involved in the reported heat-flow determination.', max_length=64, null=True, verbose_name='stratigraphic age')),
                ('T_grad_mean_meas', models.FloatField(blank=True, help_text='measured temperature gradient for the heat-flow determination interval.', null=True, verbose_name='measured gradient (K/km)')),
                ('T_grad_unc_meas', models.FloatField(blank=True, help_text='uncertainty (standard deviation) of the measured temperature gradient estimated by error propagation from uncertainty in the top and bottom interval temperatures.', null=True, verbose_name='uncertainty (K/km)')),
                ('T_grad_mean_cor', models.FloatField(blank=True, help_text='temperature gradient corrected for borehole and environmental effects. Correction method should be recorded in the relevant field.', null=True, verbose_name='corrected gradient (K/km)')),
                ('T_grad_unc_cor', models.FloatField(blank=True, help_text='uncertainty (standard deviation) of the corrected temperature gradient estimated by error propagation from uncertainty of the measured gradient and the applied correction approaches.', null=True, verbose_name='uncertainty (K/km)')),
                ('T_method_top', models.CharField(blank=True, choices=[('bht', 'Bottom hole temperature (uncorrected)'), ('cbht', 'Bottom hole temperature (corrected)'), ('dst', 'Drill stem test'), ('pt100', 'Pt-100 probe'), ('pt1000', 'Pt-1000 probe'), ('log', 'Continuous temperature log'), ('clog', 'Corrected temperature log'), ('dts', 'Distributed temperature sensing'), ('cpd', 'Cure point depth estimate'), ('xen', 'Xenlith'), ('gtm', 'Geothermometry'), ('bsr', 'Bottom-simulating seismic reflector'), ('apct/set-2', 'Ocean drilling temperature tool'), ('sur', 'Surface temperature')], help_text='Method used to determine temperature at the top of the heat flow interval.', max_length=10, null=True, verbose_name='temperature method (top)')),
                ('T_method_bot', models.CharField(blank=True, choices=[('bht', 'Bottom hole temperature (uncorrected)'), ('cbht', 'Bottom hole temperature (corrected)'), ('dst', 'Drill stem test'), ('pt100', 'Pt-100 probe'), ('pt1000', 'Pt-1000 probe'), ('log', 'Continuous temperature log'), ('clog', 'Corrected temperature log'), ('dts', 'Distributed temperature sensing'), ('cpd', 'Cure point depth estimate'), ('xen', 'Xenlith'), ('gtm', 'Geothermometry'), ('bsr', 'Bottom-simulating seismic reflector'), ('apct/set-2', 'Ocean drilling temperature tool'), ('sur', 'Surface temperature')], help_text='Method used to determine temperature at the bottom of the heat flow interval.', max_length=10, null=True, verbose_name='temperature method (bottom)')),
                ('T_shutin_top', models.PositiveSmallIntegerField(blank=True, help_text='Time of measurement at the interval top in relation to the end of drilling/end of mud circulation. Positive values are measured after the drilling, 0 represents temperatures measured during the drilling.', null=True, verbose_name='Shut-in time (top; hrs)')),
                ('T_shutin_bot', models.PositiveSmallIntegerField(blank=True, help_text='Time of measurement at the interval bottom in relation to the end of drilling/end of mud circulation. Positive values are measured after the drilling, 0 represents temperatures measured during the drilling.', null=True, verbose_name='Shut-in time (bottom; hrs)')),
                ('T_corr_top', models.CharField(blank=True, choices=[('hp', 'Horner Plot'), ('csm', 'Cylinder source method'), ('lsm', 'Line source explosion method'), ('im', 'Inverse numerical modelling'), ('other', 'Other'), ('not corrected', 'Not corrected'), ('unspecified', 'Unspecified')], help_text='Approach used at the top of the heat flow interval to correct the measured temperature for drilling perturbations.', max_length=13, null=True, verbose_name='correction method (top)')),
                ('T_corr_bot', models.CharField(blank=True, choices=[('hp', 'Horner Plot'), ('csm', 'Cylinder source method'), ('lsm', 'Line source explosion method'), ('im', 'Inverse numerical modelling'), ('other', 'Other'), ('not corrected', 'Not corrected'), ('unspecified', 'Unspecified')], help_text='Approach used at the bottom of the heat flow interval to correct the measured temperature for drilling perturbations.', max_length=13, null=True, verbose_name='correction method (bottom)')),
                ('T_numb', models.PositiveSmallIntegerField(blank=True, help_text='Number of discrete temperature points (e.g. number of used BHT values, log values or thermistors used in probe sensing) confirming the mean temperature gradient. Not the repetition of one measurement at a certain depth.', null=True, verbose_name='number of temperature recordings')),
                ('tc_mean', core.fields.RangeField(blank=True, help_text='Mean conductivity in the vertical direction representative for the heat-flow determination interval. Value should reflect true in-situ conditions for the interval.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Mean conductivity (W/mK)')),
                ('tc_unc', core.fields.RangeField(blank=True, help_text='Uncertainty of the mean thermal conductivity given as one-sigma standard deviation.', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='uncertainty')),
                ('tc_source', models.CharField(blank=True, choices=[('outcrop samples', 'Outcrop samples'), ('core samples', 'Core samples'), ('cutting samples', 'Cutting samples'), ('mineral computation', 'Mineral computation'), ('well log interpretation', 'Well log interpretation'), ('core-log integration', 'Core-log integration'), ('in-situ probe', 'In-situ probe'), ('other', 'Other (specify in comments field)'), ('unspecified', 'Unspecified')], help_text='Nature of the samples from which the mean thermal conductivity was determined', max_length=23, null=True, verbose_name='source')),
                ('tc_meth', models.CharField(blank=True, help_text='Method used to determine the mean thermal conductivity over the given interval', max_length=100, null=True, verbose_name='method')),
                ('tc_satur', models.CharField(blank=True, help_text='Saturation state of the rock sample studied for thermal conductivity', max_length=100, null=True, verbose_name='saturation state')),
                ('tc_pTcond', models.CharField(blank=True, choices=[('unrecorded ambient pt conditions', 'Unrecorded ambient pT conditions'), ('recorded ambient pt conditions', 'Recorded ambient pT conditions'), ('replicated in-situ (p)', 'Replicated in-situ (p)'), ('replicated in-situ (t)', 'Replicated in-situ (T)'), ('replicated in-situ (pt)', 'Replicated in-situ (pT)'), ('actual in-situ (pt) conditions', 'Actual in-situ (pT) conditions')], help_text='Pressure and temperature conditions under which the mean thermal conductivity for the given interval was determined. "Recorded" - determined under true conditions at target depths (e.g. sensing in boreholes), "Replicated" - determined in a laboratory under replicated in-situ conditions, "Actual" - under conditions at the respective depth of the heat-flow interval', max_length=100, null=True, verbose_name='pT conditions')),
                ('tc_pTfunc', models.CharField(blank=True, help_text='Technique or approach used to correct the measured thermal conductivity towards in-situ pT conditions', max_length=255, null=True, verbose_name='assumed pT function')),
                ('tc_strategy', models.CharField(blank=True, help_text='Strategy employed to estimate thermal conductivity over the given interval', max_length=255, null=True, verbose_name='averaging methodoloy')),
                ('tc_numb', models.PositiveSmallIntegerField(blank=True, help_text='Number of discrete temperature points (e.g. number of used BHT values, log values or thermistors used in probe sensing) confirming the mean temperature gradient. Not the repetition of one measurement at a certain depth.', null=True, verbose_name='number of temperature recordings')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('corrections', models.ManyToManyField(related_name='review_intervals', to='database.Correction', verbose_name='Applied Corrections')),
                ('reference', models.ForeignKey(help_text='The publication or other reference from which the measurement was reported.', on_delete=django.db.models.deletion.CASCADE, related_name='review_intervals', to='publications.publication', verbose_name='reference')),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_intervals', to='review.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'Heat Flow',
                'verbose_name_plural': 'Heat Flow',
                'db_table': 'heat_flow_interval_review',
                'ordering': ['date_added'],
                'abstract': False,
                'default_related_name': 'review_intervals',
            },
        ),
    ]
