# Generated by Django 3.2.15 on 2022-08-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='accepted',
            field=models.DateTimeField(blank=True, help_text='Date the review was accepted by site admins and incorporated into the production database', null=True, verbose_name='review accepted'),
        ),
    ]
