# Generated by Django 3.2.15 on 2022-08-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_review_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='nominated',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the user nominated themselves to review this publication', verbose_name='reviewer nominated'),
        ),
    ]
