# Generated by Django 3.2.15 on 2022-08-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
        ('database', '0027_auto_20220809_1708'),
        ('publications', '0009_alter_publication_abstract'),
        ('review', '0003_alter_review_nominated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interval',
            new_name='ReviewInterval',
        ),
        migrations.RenameModel(
            old_name='Site',
            new_name='ReviewSite',
        ),
    ]
