# Generated by Django 3.2.15 on 2022-08-16 09:02

from django.db import migrations, models
import django.db.models.deletion
import earth_materials.fields


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0006_earthmaterial_label'),
        ('review', '0004_auto_20220809_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinterval',
            name='bgs_lith',
            field=earth_materials.fields.EarthMaterialOneToOne(blank=True, help_text='Dominant rock type/lithology within the interval of heat-flow determination using the British Geological Society Earth Material Class (rock classification) scheme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_intervals', to='earth_materials.earthmaterial', verbose_name='lithology'),
        ),
        migrations.AlterField(
            model_name='reviewinterval',
            name='geo_lith',
            field=models.CharField(blank=True, help_text='Old lithology. Needs to be converted to BGS classification using bgs_lith field.', max_length=255, null=True, verbose_name='lithology'),
        ),
    ]
