# Generated by Django 3.2.15 on 2022-08-18 10:53

from django.db import migrations
import django.db.models.deletion
import geologic_time.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geologic_time', '0009_auto_20220818_1253'),
        ('review', '0005_auto_20220816_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewinterval',
            name='ics_strat',
            field=geologic_time.fields.GeologicTimeOneToOne(blank=True, help_text='Stratigraphic age of the depth range involved in the reported heat-flow determination based on the official geologic timescale of the International Commission on Stratigraphy.', limit_choices_to=geologic_time.fields.limit_choices_to, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_intervals', to='geologic_time.geologictime', verbose_name='ICS stratigraphy'),
        ),
    ]
