# Generated by Django 3.2.15 on 2022-08-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_tectonics', '0001_initial'),
        ('review', '0007_alter_reviewinterval_ics_strat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewsite',
            name='plate',
            field=models.ForeignKey(blank=True, help_text='tectonic plate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='global_tectonics.plate', verbose_name='plate'),
        ),
        migrations.AlterField(
            model_name='reviewsite',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_sites', to='global_tectonics.province', verbose_name='geological province'),
        ),
    ]
