# Generated by Django 3.2.15 on 2022-09-08 12:06

from django.db import migrations
import django.db.models.deletion
import earth_science.fields


class Migration(migrations.Migration):

    dependencies = [
        ('earth_science', '__first__'),
        ('review', '0008_auto_20220823_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewinterval',
            name='bgs_lith',
            field=earth_science.fields.EarthMaterialOneToOne(blank=True, help_text='Dominant rock type/lithology within the interval of heat-flow determination using the British Geological Society Earth Material Class (rock classification) scheme.', limit_choices_to=earth_science.fields.limit_choices_to, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_intervals', to='earth_science.earthmaterial', verbose_name='lithology'),
        ),
        migrations.AlterField(
            model_name='reviewinterval',
            name='ics_strat',
            field=earth_science.fields.GeologicTimeOneToOne(blank=True, help_text='Stratigraphic age of the depth range involved in the reported heat-flow determination based on the official geologic timescale of the International Commission on Stratigraphy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_intervals', to='earth_science.geologictime', verbose_name='ICS stratigraphy'),
        ),
    ]
