# Generated by Django 4.2.1 on 2023-08-09 20:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geoluminate.contrib.controlled_vocabulary.fields
import geoluminate.db.models.fields
import meta.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("controlled_vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeatFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier for this record.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "q",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="mW / m^2",
                        help_text="Measured heat flow value at the site in milliwatts per square meter (mW/m²).",
                        unit_choices=["mW / m^2"],
                        validators=[
                            django.core.validators.MinValueValidator(-1000000),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="heat flow",
                    ),
                ),
                (
                    "q_unc",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="mW / m^2",
                        blank=True,
                        help_text="Uncertainty standard deviation of the reported heat flow value as estimated by error propagation from uncertainty in thermal conductivity and temperature gradient (corrected preferred over measured gradient).",
                        null=True,
                        unit_choices=["mW / m^2"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="heat flow uncertainty",
                    ),
                ),
                (
                    "q_date_acq",
                    models.DateField(
                        help_text='Year of acquisition of the heat-flow data in the form "YYYY-MM" (may differ from publication year)',
                        null=True,
                        verbose_name="date acquired",
                    ),
                ),
                (
                    "borehole_depth",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="The total drilling depth below the ground surface level at the site.",
                        null=True,
                        unit_choices=["m"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(15000),
                        ],
                        verbose_name="total borehole depth",
                    ),
                ),
                (
                    "expedition",
                    models.CharField(
                        help_text="Specify the expedition, cruise, platform, or research vessel where the marine heat flow survey was conducted. This field applies only to marine probe sensing and drillings. Examples: Expedition cruise number OR R/V Ship OR D/V Platform.",
                        max_length=255,
                        null=True,
                        verbose_name="expedition/platform/ship",
                    ),
                ),
                (
                    "water_temp",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="°C",
                        blank=True,
                        help_text="Seafloor temperature where the heat flow measurement was made.",
                        null=True,
                        unit_choices=["°C", "K"],
                        verbose_name="bottom water temperature",
                    ),
                ),
                (
                    "environment",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        blank=True,
                        help_text="Describes the general geographical setting of the heat flow site (not the applied methodology).",
                        limit_choices_to={"label": "environment"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        verbose_name="basic geographical environment",
                        vocab_label="environment",
                    ),
                ),
                (
                    "explo_method",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        blank=True,
                        help_text="Indicates the general method by which the rock was accessed by temperature sensors.",
                        limit_choices_to={"label": "explo_method"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        verbose_name="exploration method",
                        vocab_label="explo_method",
                    ),
                ),
                (
                    "explo_purpose",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        blank=True,
                        help_text="The primary objective of the original exploration, which allowed access for placement of temperature sensors.",
                        limit_choices_to={"label": "explo_purpose"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        verbose_name="exploration purpose",
                        vocab_label="explo_purpose",
                    ),
                ),
            ],
            options={
                "verbose_name": "Heat Flow",
                "verbose_name_plural": "Heat Flow (Parent)",
                "db_table": "global_heat_flow",
                "default_related_name": "sites",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name="Interval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier for this record.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "qc",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="mW / m^2",
                        help_text="child heat flow value",
                        unit_choices=["mW / m^2"],
                        validators=[
                            django.core.validators.MinValueValidator(-1000000),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="heat flow",
                    ),
                ),
                (
                    "qc_unc",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="mW / m^2",
                        blank=True,
                        help_text="uncertainty standard deviation of the reported heat-flow value as estimated by an error propagation from uncertainty in thermal conductivity and temperature gradient (corrected preferred over measured gradient).",
                        null=True,
                        unit_choices=["mW / m^2"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="heat flow uncertainty",
                    ),
                ),
                (
                    "q_top",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="Specifies the true vertical depth at the top of the heat-flow interval relative to land surface/ocean bottom.",
                        null=True,
                        unit_choices=["m"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="interval top",
                    ),
                ),
                (
                    "q_bot",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="Describes the true vertical depth of the bottom end of the heat-flow determination interval relative to the land surface/ocean bottom.",
                        null=True,
                        unit_choices=["m"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10000),
                        ],
                        verbose_name="interval bottom",
                    ),
                ),
                (
                    "hf_pen",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="Depth of penetration of marine probe into the sediment.",
                        null=True,
                        unit_choices=["m"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="penetration depth",
                    ),
                ),
                (
                    "hf_probeL",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="m",
                        blank=True,
                        help_text="length of the marine probe.",
                        null=True,
                        unit_choices=["m"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="probe length",
                    ),
                ),
                (
                    "probe_tilt",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="degree",
                        blank=True,
                        help_text="Tilt of the marine probe.",
                        null=True,
                        unit_choices=["degree"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="tilt",
                    ),
                ),
                (
                    "q_date_acq",
                    models.DateField(
                        blank=True,
                        help_text="Year of acquisition of the heat-flow data (may differ from publication year)",
                        null=True,
                        verbose_name="date of acquisition (YYYY-MM)",
                    ),
                ),
                (
                    "relevant_child",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Specify whether the child entry is used for computation of representative location heat flow values at the parent level or not.",
                        null=True,
                        verbose_name="Is relevant child?",
                    ),
                ),
                (
                    "tc_mean",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="W/mK",
                        blank=True,
                        help_text="Mean conductivity in the vertical direction representative for the heat-flow determination interval. Value should reflect true in-situ conditions for the interval.",
                        null=True,
                        unit_choices=["W/mK"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Mean conductivity",
                    ),
                ),
                (
                    "tc_uncertainty",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="W/mK",
                        blank=True,
                        help_text="Uncertainty of the mean thermal conductivity given as one-sigma standard deviation.",
                        null=True,
                        unit_choices=["W/mK"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="uncertainty",
                    ),
                ),
                (
                    "tc_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used to determine the mean thermal conductivity over the given interval",
                        max_length=100,
                        null=True,
                        verbose_name="method",
                    ),
                ),
                (
                    "tc_saturation",
                    models.CharField(
                        blank=True,
                        help_text="Saturation state of the rock sample studied for thermal conductivity",
                        max_length=100,
                        null=True,
                        verbose_name="saturation state",
                    ),
                ),
                (
                    "tc_pT_function",
                    models.CharField(
                        blank=True,
                        help_text="Technique or approach used to correct the measured thermal conductivity towards in-situ pT conditions",
                        max_length=255,
                        null=True,
                        verbose_name="assumed pT function",
                    ),
                ),
                (
                    "tc_strategy",
                    models.CharField(
                        blank=True,
                        help_text="Strategy employed to estimate thermal conductivity over the given interval",
                        max_length=255,
                        null=True,
                        verbose_name="averaging methodoloy",
                    ),
                ),
                (
                    "tc_count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of discrete temperature points (e.g. number of used BHT values, log values or thermistors used in probe sensing) confirming the mean temperature gradient. Not the repetition of one measurement at a certain depth.",
                        null=True,
                        verbose_name="number of temperature recordings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interval",
                "verbose_name_plural": "Heat Flow (Child)",
                "db_table": "heat_flow_interval",
                "ordering": ["relevant_child", "q_top"],
                "default_related_name": "intervals",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name="Temperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier for this record.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "grad_mean",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="K/km",
                        blank=True,
                        help_text="measured temperature gradient for the heat-flow determination interval.",
                        null=True,
                        unit_choices=["K/km"],
                        verbose_name="measured gradient",
                    ),
                ),
                (
                    "grad_uncertainty",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="K/km",
                        blank=True,
                        help_text="uncertainty (standard deviation) of the measured temperature gradient estimated by error propagation from uncertainty in the top and bottom interval temperatures.",
                        null=True,
                        unit_choices=["K/km"],
                        verbose_name="uncertainty",
                    ),
                ),
                (
                    "grad_mean_cor",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="K/km",
                        blank=True,
                        help_text="temperature gradient corrected for borehole and environmental effects. Correction method should be recorded in the relevant field.",
                        null=True,
                        unit_choices=["K/km"],
                        verbose_name="corrected gradient",
                    ),
                ),
                (
                    "grad_uncertainty_cor",
                    geoluminate.db.models.fields.QuantityField(
                        base_units="K/km",
                        blank=True,
                        help_text="uncertainty (standard deviation) of the corrected temperature gradient estimated by error propagation from uncertainty of the measured gradient and the applied correction approaches.",
                        null=True,
                        unit_choices=["K/km"],
                        verbose_name="uncertainty",
                    ),
                ),
                (
                    "shutin_top",
                    geoluminate.db.models.fields.PositiveIntegerQuantityField(
                        base_units="hour",
                        blank=True,
                        help_text="Time of measurement at the interval top in relation to the end of drilling/end of mud circulation. Positive values are measured after the drilling, 0 represents temperatures measured during the drilling.",
                        null=True,
                        unit_choices=["hour"],
                        verbose_name="Shut-in time (top)",
                    ),
                ),
                (
                    "shutin_bottom",
                    geoluminate.db.models.fields.PositiveIntegerQuantityField(
                        base_units="hour",
                        blank=True,
                        help_text="Time of measurement at the interval bottom in relation to the end of drilling/end of mud circulation. Positive values are measured after the drilling, 0 represents temperatures measured during the drilling.",
                        null=True,
                        unit_choices=["hour"],
                        verbose_name="Shut-in time (bottom; hrs)",
                    ),
                ),
                (
                    "count",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Number of discrete temperature points (e.g. number of used BHT values, log values or thermistors used in probe sensing) confirming the mean temperature gradient. Not the repetition of one measurement at a certain depth.",
                        null=True,
                        verbose_name="number of temperature recordings",
                    ),
                ),
                (
                    "correction_bottom",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        blank=True,
                        help_text="Approach used at the bottom of the heat flow interval to correct the measured temperature for drilling perturbations.",
                        limit_choices_to={"label": "T_correction_method"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        verbose_name="correction method (bottom)",
                        vocab_label="T_correction_method",
                    ),
                ),
                (
                    "correction_top",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        blank=True,
                        help_text="Approach used at the top of the heat flow interval to correct the measured temperature for drilling perturbations.",
                        limit_choices_to={"label": "T_correction_method"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        verbose_name="correction method (top)",
                        vocab_label="T_correction_method",
                    ),
                ),
                (
                    "interval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp",
                        to="heat_flow.interval",
                    ),
                ),
                (
                    "method_bottom",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        blank=True,
                        help_text="Method used to determine temperature at the bottom of the heat flow interval.",
                        limit_choices_to={"label": "T_method"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        verbose_name="temperature method (bottom)",
                        vocab_label="T_method",
                    ),
                ),
                (
                    "method_top",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        blank=True,
                        help_text="Method used to determine temperature at the top of the heat flow interval.",
                        limit_choices_to={"label": "T_method"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        verbose_name="temperature method (top)",
                        vocab_label="T_method",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature",
                "verbose_name_plural": "Temperature Data",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.CreateModel(
            name="IntervalCorrectionThrough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Universally unique identifier for this record.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was created.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this record was last modified.",
                        verbose_name="Modified",
                    ),
                ),
                (
                    "applied",
                    models.CharField(
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("mentioned", "Mentioned in-text but unclear if applied"),
                        ],
                        help_text="Has the correction been applied to this interval?",
                        max_length=9,
                        verbose_name="Applied?",
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        blank=True,
                        help_text="Value of the applied correction in (mW m^-2). Can be positive or negative.",
                        null=True,
                        verbose_name="value",
                    ),
                ),
                (
                    "correction",
                    geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                        limit_choices_to={"label": "correction"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="controlled_vocabulary.controlledvocabulary",
                        vocab_label="correction",
                    ),
                ),
                (
                    "interval",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="heat_flow.interval",
                    ),
                ),
            ],
            options={
                "verbose_name": "correction",
                "verbose_name_plural": "corrections",
            },
            bases=(meta.models.ModelMeta, models.Model),
        ),
        migrations.AddField(
            model_name="interval",
            name="corrections",
            field=models.ManyToManyField(
                blank=True,
                through="heat_flow.IntervalCorrectionThrough",
                to="controlled_vocabulary.controlledvocabulary",
                verbose_name="Applied Corrections",
            ),
        ),
        migrations.AddField(
            model_name="interval",
            name="hf_probe",
            field=geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                blank=True,
                help_text="Type of marine probe used for measurement.",
                limit_choices_to={"label": "hf_probe"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="controlled_vocabulary.controlledvocabulary",
                verbose_name="probe type",
                vocab_label="hf_probe",
            ),
        ),
        migrations.AddField(
            model_name="interval",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="parent heat flow site",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervals",
                to="heat_flow.heatflow",
                verbose_name="parent",
            ),
        ),
        migrations.AddField(
            model_name="interval",
            name="q_method",
            field=geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                blank=True,
                help_text="Principal method of heat-flow density calculation from temperature and thermal conductivity data",
                limit_choices_to={"label": "q_method"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="controlled_vocabulary.controlledvocabulary",
                verbose_name="method",
                vocab_label="q_method",
            ),
        ),
        migrations.AddField(
            model_name="interval",
            name="q_tf_mech",
            field=geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                blank=True,
                help_text="Specification of the predominant heat transfer mechanism relevant to the reported heat flow value.",
                limit_choices_to={"label": "q_tf_mech"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="controlled_vocabulary.controlledvocabulary",
                verbose_name="transfer mechanism",
                vocab_label="q_tf_mech",
            ),
        ),
        migrations.AddField(
            model_name="interval",
            name="tc_pT_conditions",
            field=geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                blank=True,
                help_text='Pressure and temperature conditions under which the mean thermal conductivity for the given interval was determined. "Recorded" - determined under true conditions at target depths (e.g. sensing in boreholes), "Replicated" - determined in a laboratory under replicated in-situ conditions, "Actual" - under conditions at the respective depth of the heat-flow interval',
                limit_choices_to={"label": "tc_pT_conditions"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="controlled_vocabulary.controlledvocabulary",
                verbose_name="pT conditions",
                vocab_label="tc_pT_conditions",
            ),
        ),
        migrations.AddField(
            model_name="interval",
            name="tc_source",
            field=geoluminate.contrib.controlled_vocabulary.fields.VocabularyField(
                blank=True,
                help_text="Nature of the samples from which the mean thermal conductivity was determined",
                limit_choices_to={"label": "tc_source"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="controlled_vocabulary.controlledvocabulary",
                verbose_name="source",
                vocab_label="tc_source",
            ),
        ),
    ]
