# Generated by Django 4.2.5 on 2023-10-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("heat_flow", "0001_initial"),
        ("samples", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heatflowchild",
            name="sample",
            field=models.ForeignKey(
                help_text="The sample on which the measurement was made.",
                on_delete=django.db.models.deletion.PROTECT,
                to="samples.sample",
                verbose_name="sample",
            ),
        ),
        migrations.AddField(
            model_name="heatflow",
            name="sample",
            field=models.ForeignKey(
                help_text="The sample on which the measurement was made.",
                on_delete=django.db.models.deletion.PROTECT,
                to="samples.sample",
                verbose_name="sample",
            ),
        ),
    ]
