# Generated by Django 4.2.1 on 2023-07-11 10:30

from django.db import migrations
import django.db.models.deletion
import geoluminate.contrib.gis.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("heat_flow", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="heatflow",
            name="site",
            field=geoluminate.contrib.gis.fields.SiteField(
                help_text="The physical site from which the heat flow measurement was derived",
                on_delete=django.db.models.deletion.PROTECT,
                to="project.site",
                verbose_name="site",
            ),
        ),
    ]
