# Generated by Django 3.2.15 on 2022-09-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_squashed_0037_auto_20220908_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterval',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last modified'),
        ),
    ]
