# Generated by Django 3.2.14 on 2022-07-08 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mapping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='reference',
            field=models.ManyToManyField(blank=True, help_text='The reference or publication from which the data were sourced. Each site may have multiple references.', related_name='sites', to='publications.Publication', verbose_name='references'),
        ),
        migrations.AddField(
            model_name='interval',
            name='reference',
            field=models.ForeignKey(help_text='The publication or other reference from which the measurement was reported.', on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='publications.publication', verbose_name='reference'),
        ),
        migrations.AddField(
            model_name='interval',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervals', to='database.site', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='continent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Continent land boundaries', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.continent', verbose_name='continent'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Country land boundaries', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='ocean',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Global oceans and seas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.ocean', verbose_name='ocean'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='plate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='tectonic plate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.plate', verbose_name='plate'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='political',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Countries inclusive of exclusive marine economic zones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.political', verbose_name='political region'),
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='province',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.province', verbose_name='geological province'),
        ),
        migrations.AddField(
            model_name='historicalinterval',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinterval',
            name='reference',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='publications.publication', verbose_name='reference'),
        ),
        migrations.AddField(
            model_name='historicalinterval',
            name='site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.site', verbose_name='site'),
        ),
        migrations.AddField(
            model_name='correction',
            name='interval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='database.interval', verbose_name='interval'),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('name', 'lat', 'lng')},
        ),
    ]
