# Generated by Django 3.2.14 on 2022-07-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterval',
            name='T_corr_bot',
            field=models.CharField(choices=[('hp', 'Horner Plot'), ('csm', 'Cylinder source method'), ('lsm', 'Line source explosion method'), ('im', 'Inverse numerical modelling'), ('other', 'Other'), ('not corrected', 'Not corrected'), ('unspecified', 'Unspecified')], help_text='Approach used at the bottom of the heat flow interval to correct the measured temperature for drilling perturbations.', max_length=13, verbose_name='correction method (bottom)'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='T_corr_top',
            field=models.CharField(choices=[('hp', 'Horner Plot'), ('csm', 'Cylinder source method'), ('lsm', 'Line source explosion method'), ('im', 'Inverse numerical modelling'), ('other', 'Other'), ('not corrected', 'Not corrected'), ('unspecified', 'Unspecified')], help_text='Approach used at the top of the heat flow interval to correct the measured temperature for drilling perturbations.', max_length=13, verbose_name='correction method (top)'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='hf_probe',
            field=models.CharField(blank=True, choices=[('corer-outrigger', 'Corer-outrigger'), ('bullard', 'Bullard Probe'), ('lister/violin', 'Lister Violin-Bow Probe'), ('ewing', 'Ewing Probe'), ('other', 'Other'), ('unspecified', 'Unspecified')], help_text='Type of marine probe used for measurement.', max_length=15, null=True, verbose_name='probe type'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='q_method',
            field=models.CharField(choices=[('fourier', "Fourier's Law"), ('product', 'Product method'), ('interval', 'Interval method'), ('bullard', 'Bullard'), ('bootsrap', 'Bootstrap')], help_text='Principal method of heat-flow density calculation from temperature and thermal conductivity data', max_length=8, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='q_tf_mech',
            field=models.CharField(blank=True, choices=[('conductive', 'Conductive'), ('convective unspecified', 'Convective - unspecified'), ('convective upflow', 'Convective - upflow'), ('convective downflow', 'Convective - downflow'), ('unspecified', 'Unspecified')], help_text='Specification of the predominant heat transfer mechanism relevant to the reported heat flow value.', max_length=22, null=True, verbose_name='transfer mechanism'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='tc_source',
            field=models.CharField(choices=[('outcrop samples', 'Outcrop samples'), ('core samples', 'Core samples'), ('cutting samples', 'Cutting samples'), ('mineral computation', 'Mineral computation'), ('well log interpretation', 'Well log interpretation'), ('core-log integration', 'Core-log integration'), ('in-situ probe', 'In-situ probe'), ('other', 'Other (specify in comments field)'), ('unspecified', 'Unspecified')], help_text='Nature of the samples from which the mean thermal conductivity was determined', max_length=23, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='env',
            field=models.CharField(choices=[('onshore (continental)', 'Onshore (Continental)'), ('onshore (lake)', 'Onshore (Lake)'), ('offshore (continental)', 'Offshore (Continental)'), ('offshore (marine)', 'Offshore (Marine)'), ('unspecified', 'Unspecified')], default='unspecified', help_text='Describes the general geographical setting of the heat-flow site (not the applied methodology).', max_length=22, verbose_name='basic geographical environment'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='expl',
            field=models.CharField(blank=True, choices=[('hydrocarbon', 'Hydrocarbon'), ('underground storage', 'Underground Storage'), ('geothermal', 'Geothermal'), ('mapping', 'Mapping'), ('mining', 'Mining'), ('tunneling', 'Tunneling'), ('unspecified', 'Unspecified')], help_text='Main purpose of the original excavation providing access for the temperature sensors.', max_length=19, null=True, verbose_name='exploration purpose'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='method',
            field=models.CharField(blank=True, choices=[('drilling', 'Drilling'), ('mining', 'Mining'), ('tunneling', 'Tunneling'), ('probing (lake)', 'Probing (Lake)'), ('probing (ocean)', 'Probing (Ocean)'), ('unspecified', 'Unspecified')], help_text='Specification of the general means by which the rock was accessed by temperature sensors for the respective data entry.', max_length=15, null=True, verbose_name='exploration method'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='T_corr_bot',
            field=models.CharField(choices=[('hp', 'Horner Plot'), ('csm', 'Cylinder source method'), ('lsm', 'Line source explosion method'), ('im', 'Inverse numerical modelling'), ('other', 'Other'), ('not corrected', 'Not corrected'), ('unspecified', 'Unspecified')], help_text='Approach used at the bottom of the heat flow interval to correct the measured temperature for drilling perturbations.', max_length=13, verbose_name='correction method (bottom)'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='T_corr_top',
            field=models.CharField(choices=[('hp', 'Horner Plot'), ('csm', 'Cylinder source method'), ('lsm', 'Line source explosion method'), ('im', 'Inverse numerical modelling'), ('other', 'Other'), ('not corrected', 'Not corrected'), ('unspecified', 'Unspecified')], help_text='Approach used at the top of the heat flow interval to correct the measured temperature for drilling perturbations.', max_length=13, verbose_name='correction method (top)'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='hf_probe',
            field=models.CharField(blank=True, choices=[('corer-outrigger', 'Corer-outrigger'), ('bullard', 'Bullard Probe'), ('lister/violin', 'Lister Violin-Bow Probe'), ('ewing', 'Ewing Probe'), ('other', 'Other'), ('unspecified', 'Unspecified')], help_text='Type of marine probe used for measurement.', max_length=15, null=True, verbose_name='probe type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='q_method',
            field=models.CharField(choices=[('fourier', "Fourier's Law"), ('product', 'Product method'), ('interval', 'Interval method'), ('bullard', 'Bullard'), ('bootsrap', 'Bootstrap')], help_text='Principal method of heat-flow density calculation from temperature and thermal conductivity data', max_length=8, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='q_tf_mech',
            field=models.CharField(blank=True, choices=[('conductive', 'Conductive'), ('convective unspecified', 'Convective - unspecified'), ('convective upflow', 'Convective - upflow'), ('convective downflow', 'Convective - downflow'), ('unspecified', 'Unspecified')], help_text='Specification of the predominant heat transfer mechanism relevant to the reported heat flow value.', max_length=22, null=True, verbose_name='transfer mechanism'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='tc_source',
            field=models.CharField(choices=[('outcrop samples', 'Outcrop samples'), ('core samples', 'Core samples'), ('cutting samples', 'Cutting samples'), ('mineral computation', 'Mineral computation'), ('well log interpretation', 'Well log interpretation'), ('core-log integration', 'Core-log integration'), ('in-situ probe', 'In-situ probe'), ('other', 'Other (specify in comments field)'), ('unspecified', 'Unspecified')], help_text='Nature of the samples from which the mean thermal conductivity was determined', max_length=23, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='site',
            name='env',
            field=models.CharField(choices=[('onshore (continental)', 'Onshore (Continental)'), ('onshore (lake)', 'Onshore (Lake)'), ('offshore (continental)', 'Offshore (Continental)'), ('offshore (marine)', 'Offshore (Marine)'), ('unspecified', 'Unspecified')], default='unspecified', help_text='Describes the general geographical setting of the heat-flow site (not the applied methodology).', max_length=22, verbose_name='basic geographical environment'),
        ),
        migrations.AlterField(
            model_name='site',
            name='expl',
            field=models.CharField(blank=True, choices=[('hydrocarbon', 'Hydrocarbon'), ('underground storage', 'Underground Storage'), ('geothermal', 'Geothermal'), ('mapping', 'Mapping'), ('mining', 'Mining'), ('tunneling', 'Tunneling'), ('unspecified', 'Unspecified')], help_text='Main purpose of the original excavation providing access for the temperature sensors.', max_length=19, null=True, verbose_name='exploration purpose'),
        ),
        migrations.AlterField(
            model_name='site',
            name='method',
            field=models.CharField(blank=True, choices=[('drilling', 'Drilling'), ('mining', 'Mining'), ('tunneling', 'Tunneling'), ('probing (lake)', 'Probing (Lake)'), ('probing (ocean)', 'Probing (Ocean)'), ('unspecified', 'Unspecified')], help_text='Specification of the general means by which the rock was accessed by temperature sensors for the respective data entry.', max_length=15, null=True, verbose_name='exploration method'),
        ),
    ]
