# Generated by Django 3.2.15 on 2022-09-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='date added'),
        ),
    ]
