# Generated by Django 3.2.15 on 2022-09-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_site_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='last modified'),
        ),
    ]
