# Generated by Django 3.2.14 on 2022-07-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_reference_site_references'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='value',
        ),
        migrations.AlterField(
            model_name='correction',
            name='type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('heat production', 'Heat Production'), ('sedimentation', 'Sedimentation'), ('erosion', 'Erosion'), ('topographic', 'Topographic'), ('climatic', 'Transient climatic'), ('convection', 'Convection processes'), ('bwt', 'Bottom water temperature variation'), ('heat refraction', 'Heat refraction')], max_length=15, verbose_name='correction type'),
        ),
    ]
