# Generated by Django 3.2.14 on 2022-07-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20220711_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='correction',
            name='applied',
            field=models.BooleanField(default=True, verbose_name='applied'),
            preserve_default=False,
        ),
    ]
