# Generated by Django 3.2.14 on 2022-07-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_correction_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='applied',
            field=models.BooleanField(default=True, verbose_name='applied?'),
        ),
    ]
