# Generated by Django 3.2.14 on 2022-07-12 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_correction_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='database.interval', verbose_name='interval'),
        ),
    ]
