# Generated by Django 3.2.14 on 2022-07-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_correction_interval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correction',
            name='interval',
        ),
        migrations.AlterField(
            model_name='correction',
            name='applied',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='applied?'),
        ),
    ]
