# Generated by Django 3.2.14 on 2022-07-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20220712_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interval',
            options={'default_related_name': 'heat_flow', 'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='interval',
            name='corrections',
            field=models.ManyToManyField(related_name='heat_flow', to='database.Correction', verbose_name='Applied Corrections'),
        ),
    ]
