# Generated by Django 3.2.14 on 2022-07-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20220712_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heat_flow', to='database.site', verbose_name='site'),
        ),
    ]
