# Generated by Django 3.2.14 on 2022-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_correction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='type',
            field=models.CharField(choices=[('IS', 'In-situ thermal properties'), ('T', 'Temperature'), ('HP', 'Heat Production'), ('S', 'Sedimentation'), ('E', 'Erosion'), ('TOPO', 'Topographic'), ('PAL', 'Transient climatic'), ('CONV', 'Convection processes'), ('BWT', 'Bottom water temperature variation'), ('HR', 'Heat refraction')], max_length=15, verbose_name='correction type'),
        ),
    ]
