# Generated by Django 3.2.14 on 2022-07-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_correction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='type',
            field=models.CharField(choices=[('in-situ thermal', 'In-situ thermal properties'), ('temperature', 'Temperature'), ('heat production', 'Heat Production'), ('sedimentation', 'Sedimentation'), ('erosion', 'Erosion'), ('topographic', 'Topographic'), ('climatic', 'Transient climatic'), ('convection', 'Convection processes'), ('bwt', 'Bottom water temperature variation'), ('heat refraction', 'Heat refraction')], max_length=15, verbose_name='correction type'),
        ),
    ]
