# Generated by Django 3.2.14 on 2022-07-12 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_correction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interval',
            options={'default_related_name': 'intervals', 'ordering': ['date_added']},
        ),
        migrations.RemoveField(
            model_name='correction',
            name='applied',
        ),
        migrations.AlterField(
            model_name='correction',
            name='type',
            field=models.CharField(choices=[('IS', 'In-situ thermal properties'), ('T', 'Temperature'), ('HP', 'Heat production'), ('S', 'Sedimentation'), ('E', 'Erosion'), ('TOPO', 'Topographic'), ('PAL', 'Transient climatic'), ('CONV', 'Convection processes'), ('BWT', 'Bottom water temperature variation'), ('HR', 'Heat refraction')], max_length=15, verbose_name='correction type'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='corrections',
            field=models.ManyToManyField(related_name='intervals', to='database.Correction', verbose_name='Applied Corrections'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervals', to='database.site', verbose_name='site'),
        ),
    ]
