# Generated by Django 3.2.14 on 2022-07-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20220712_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='correction',
            name='type',
            field=models.CharField(max_length=64, verbose_name='correction type'),
        ),
    ]
