# Generated by Django 3.2.14 on 2022-07-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20220712_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='q_acq',
            field=models.DateField(help_text='Year of acquisition of the heat-flow data (may differ from publication year)', null=True, verbose_name='date of acquisition (YYYY-MM)'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='q_acq',
            field=models.DateField(help_text='Year of acquisition of the heat-flow data in the form "YYYY-MM" (may differ from publication year)', null=True, verbose_name='date acquired'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='q_acq',
            field=models.DateField(help_text='Year of acquisition of the heat-flow data (may differ from publication year)', null=True, verbose_name='date of acquisition (YYYY-MM)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='q_acq',
            field=models.DateField(help_text='Year of acquisition of the heat-flow data in the form "YYYY-MM" (may differ from publication year)', null=True, verbose_name='date acquired'),
        ),
    ]
