# Generated by Django 3.2.14 on 2022-07-13 12:22

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20220713_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterval',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', db_index=True, length=8, max_length=15, prefix='GHFI-'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='q_method',
            field=models.CharField(choices=[('fourier', "Fourier's Law"), ('product', 'Product method'), ('interval', 'Interval method'), ('bullard', 'Bullard'), ('bootsrap', 'Bootstrap')], help_text='Principal method of heat-flow density calculation from temperature and thermal conductivity data', max_length=8, null=True, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', length=8, max_length=15, prefix='GHFI-', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interval',
            name='q_method',
            field=models.CharField(choices=[('fourier', "Fourier's Law"), ('product', 'Product method'), ('interval', 'Interval method'), ('bullard', 'Bullard'), ('bootsrap', 'Bootstrap')], help_text='Principal method of heat-flow density calculation from temperature and thermal conductivity data', max_length=8, null=True, verbose_name='method'),
        ),
    ]
