# Generated by Django 3.2.14 on 2022-07-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_auto_20220713_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
    ]
