# Generated by Django 3.2.14 on 2022-07-13 14:27

import core.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_auto_20220713_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterval',
            name='q_top',
            field=core.fields.RangeField(blank=True, help_text='Describes the true vertical depth of the top end of the heat-flow determination interval relative to the land surface/ocean bottom.', null=True, validators=[django.core.validators.MaxValueValidator(12500), django.core.validators.MinValueValidator(-1000)], verbose_name='interval top (m)'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='q_top',
            field=core.fields.RangeField(blank=True, help_text='Describes the true vertical depth of the top end of the heat-flow determination interval relative to the land surface/ocean bottom.', null=True, validators=[django.core.validators.MaxValueValidator(12500), django.core.validators.MinValueValidator(-1000)], verbose_name='interval top (m)'),
        ),
    ]
