# Generated by Django 3.2.14 on 2022-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_auto_20220713_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterval',
            name='historic_id',
            field=models.PositiveIntegerField(blank=True, help_text='This is the numeric identifier used in old forms of the GHFDB to identify measurements', null=True, verbose_name='Historic ID'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='historic_id',
            field=models.PositiveIntegerField(blank=True, help_text='This is the numeric identifier used in old forms of the GHFDB to identify measurements', null=True, verbose_name='Historic ID'),
        ),
    ]
