# Generated by Django 3.2.14 on 2022-07-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_auto_20220714_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterval',
            name='tc_pTcond',
            field=models.CharField(blank=True, choices=[('unrecorded ambient pt conditions', 'Unrecorded ambient pT conditions'), ('recorded ambient pt conditions', 'Recorded ambient pT conditions'), ('replicated in-situ (p)', 'Replicated in-situ (p)'), ('replicated in-situ (t)', 'Replicated in-situ (T)'), ('replicated in-situ (pt)', 'Replicated in-situ (pT)'), ('actual in-situ (pt) conditions', 'Actual in-situ (pT) conditions')], help_text='Pressure and temperature conditions under which the mean thermal conductivity for the given interval was determined. "Recorded" - determined under true conditions at target depths (e.g. sensing in boreholes), "Replicated" - determined in a laboratory under replicated in-situ conditions, "Actual" - under conditions at the respective depth of the heat-flow interval', max_length=100, null=True, verbose_name='pT conditions'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='tc_pTcond',
            field=models.CharField(blank=True, choices=[('unrecorded ambient pt conditions', 'Unrecorded ambient pT conditions'), ('recorded ambient pt conditions', 'Recorded ambient pT conditions'), ('replicated in-situ (p)', 'Replicated in-situ (p)'), ('replicated in-situ (t)', 'Replicated in-situ (T)'), ('replicated in-situ (pt)', 'Replicated in-situ (pT)'), ('actual in-situ (pt) conditions', 'Actual in-situ (pT) conditions')], help_text='Pressure and temperature conditions under which the mean thermal conductivity for the given interval was determined. "Recorded" - determined under true conditions at target depths (e.g. sensing in boreholes), "Replicated" - determined in a laboratory under replicated in-situ conditions, "Actual" - under conditions at the respective depth of the heat-flow interval', max_length=100, null=True, verbose_name='pT conditions'),
        ),
    ]
