# Generated by Django 3.2.15 on 2022-08-05 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0025_auto_20220714_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsite',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Site', 'verbose_name_plural': 'historical Sites'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'default_related_name': 'sites', 'ordering': ['-date_added'], 'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AddField(
            model_name='historicalinterval',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 14, 45, 45, 868564, tzinfo=utc), editable=False, verbose_name='last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 5, 14, 45, 58, 194381, tzinfo=utc), editable=False, verbose_name='last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
        migrations.AddField(
            model_name='site',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
