# Generated by Django 3.2.15 on 2022-08-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_auto_20220805_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalinterval',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Heat Flow', 'verbose_name_plural': 'historical Heat Flow'},
        ),
        migrations.AlterModelOptions(
            name='interval',
            options={'default_related_name': 'intervals', 'ordering': ['date_added'], 'verbose_name': 'Heat Flow', 'verbose_name_plural': 'Heat Flow'},
        ),
    ]
