# Generated by Django 3.2.15 on 2022-08-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0003_auto_20220815_1143'),
        ('database', '0027_auto_20220809_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinterval',
            name='bgs_lith',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dominant rock type/lithology within the interval of heat-flow determination using the British Geological Society Earth Material Class (rock classification) scheme.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='earth_materials.earthmaterial', verbose_name='lithology'),
        ),
        migrations.AddField(
            model_name='interval',
            name='bgs_lith',
            field=models.OneToOneField(blank=True, help_text='Dominant rock type/lithology within the interval of heat-flow determination using the British Geological Society Earth Material Class (rock classification) scheme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervals', to='earth_materials.earthmaterial', verbose_name='lithology'),
        ),
        migrations.AlterField(
            model_name='historicalinterval',
            name='geo_lith',
            field=models.CharField(blank=True, help_text='Old lithology. Needs to be converted to BGS classification using bgs_lith field.', max_length=255, null=True, verbose_name='lithology'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='geo_lith',
            field=models.CharField(blank=True, help_text='Old lithology. Needs to be converted to BGS classification using bgs_lith field.', max_length=255, null=True, verbose_name='lithology'),
        ),
    ]
