# Generated by Django 3.2.15 on 2022-08-15 12:30

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0005_alter_earthmaterial_options'),
        ('database', '0028_auto_20220815_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='bgs_lith',
            field=treewidget.fields.TreeOneToOneField(blank=True, help_text='Dominant rock type/lithology within the interval of heat-flow determination using the British Geological Society Earth Material Class (rock classification) scheme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervals', to='earth_materials.earthmaterial', verbose_name='lithology'),
        ),
    ]
