# Generated by Django 3.2.15 on 2022-08-16 09:02

from django.db import migrations
import django.db.models.deletion
import earth_materials.fields


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0006_earthmaterial_label'),
        ('database', '0029_alter_interval_bgs_lith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='bgs_lith',
            field=earth_materials.fields.EarthMaterialOneToOne(blank=True, help_text='Dominant rock type/lithology within the interval of heat-flow determination using the British Geological Society Earth Material Class (rock classification) scheme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervals', to='earth_materials.earthmaterial', verbose_name='lithology'),
        ),
    ]
