# Generated by Django 3.2.15 on 2022-08-17 13:21

from django.db import migrations, models
import django.db.models.deletion
import earth_materials.fields


class Migration(migrations.Migration):

    dependencies = [
        ('earth_materials', '0006_earthmaterial_label'),
        ('database', '0030_alter_interval_bgs_lith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinterval',
            name='bgs_lith',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Dominant rock type/lithology within the interval of heat-flow determination using the British Geological Society Earth Material Class (rock classification) scheme.', limit_choices_to=earth_materials.fields.material_type_limiter, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='earth_materials.earthmaterial', verbose_name='lithology'),
        ),
    ]
