# Generated by Django 3.2.15 on 2022-08-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('global_tectonics', '0001_initial'),
        ('database', '0033_auto_20220823_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='plate',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='tectonic plate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='global_tectonics.plate', verbose_name='plate'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='province',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='global_tectonics.province', verbose_name='geological province'),
        ),
        migrations.AlterField(
            model_name='site',
            name='plate',
            field=models.ForeignKey(blank=True, help_text='tectonic plate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='global_tectonics.plate', verbose_name='plate'),
        ),
        migrations.AlterField(
            model_name='site',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='global_tectonics.province', verbose_name='geological province'),
        ),
    ]
