# Generated by Django 3.2.15 on 2022-09-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_conductivitysource_correctiontype_explorationmethod_explorationpurpose_geographicenvironment_heatflo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConductivitySource',
        ),
        migrations.DeleteModel(
            name='CorrectionType',
        ),
        migrations.DeleteModel(
            name='ExplorationMethod',
        ),
        migrations.DeleteModel(
            name='ExplorationPurpose',
        ),
        migrations.DeleteModel(
            name='GeographicEnvironment',
        ),
        migrations.DeleteModel(
            name='HeatFlowMethod',
        ),
        migrations.DeleteModel(
            name='HeatTransfer',
        ),
        migrations.DeleteModel(
            name='ProbeType',
        ),
        migrations.DeleteModel(
            name='TC_PT_Conditions',
        ),
        migrations.DeleteModel(
            name='TC_SaturationMethod',
        ),
        migrations.DeleteModel(
            name='TempCorrectionMethod',
        ),
        migrations.DeleteModel(
            name='TempMethod',
        ),
    ]
