# Generated by Django 3.2.8 on 2021-10-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsite',
            name='site_name',
            field=models.CharField(help_text='The name given to the site.', max_length=200, null=True, verbose_name='site name'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_name',
            field=models.CharField(help_text='The name given to the site.', max_length=200, null=True, verbose_name='site name'),
        ),
    ]
