# Generated by Django 3.0.8 on 2020-08-25 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='bottom_water_temp',
            field=models.OneToOneField(blank=True, help_text='Temperature at the bottom of the water column.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottom_water_temp', to='thermoglobe.Temperature', verbose_name='bottom water temperature'),
        ),
    ]
