# Generated by Django 3.2.12 on 2022-02-11 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_ocean'),
        ('thermoglobe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='sea',
        ),
        migrations.RemoveField(
            model_name='site',
            name='sea',
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='ocean',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Global oceans and seas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.ocean', verbose_name='ocean'),
        ),
        migrations.AddField(
            model_name='site',
            name='ocean',
            field=models.ForeignKey(blank=True, help_text='Global oceans and seas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='mapping.ocean', verbose_name='ocean'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='continent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Continent land boundaries', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.continent', verbose_name='continent'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Country land boundaries', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='historicalsite',
            name='political',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Countries inclusive of exclusive marine economic zones', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mapping.political', verbose_name='political region'),
        ),
        migrations.AlterField(
            model_name='site',
            name='continent',
            field=models.ForeignKey(blank=True, help_text='Continent land boundaries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='mapping.continent', verbose_name='continent'),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Country land boundaries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='mapping.country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='site',
            name='political',
            field=models.ForeignKey(blank=True, help_text='Countries inclusive of exclusive marine economic zones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='mapping.political', verbose_name='political region'),
        ),
    ]
