# Generated by Django 3.2.9 on 2021-11-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0002_auto_20211028_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradient',
            fields=[
            ],
            options={
                'verbose_name': 'thermal gradient',
                'verbose_name_plural': 'thermal gradients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('thermoglobe.interval',),
        ),
        migrations.CreateModel(
            name='HeatFlow',
            fields=[
            ],
            options={
                'verbose_name': 'heat flow',
                'verbose_name_plural': 'heat flow',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('thermoglobe.interval',),
        ),
        migrations.AlterModelOptions(
            name='conductivity',
            options={'ordering': ['site__site_name', 'log_id', 'depth'], 'verbose_name': 'thermal conductivity', 'verbose_name_plural': 'thermal conductivity'},
        ),
        migrations.AlterModelOptions(
            name='heatproduction',
            options={'default_related_name': 'heat_production', 'ordering': ['log_id', 'depth'], 'verbose_name': 'heat production', 'verbose_name_plural': 'heat production'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'ordering': ['log_id', 'depth'], 'verbose_name': 'temperature', 'verbose_name_plural': 'temperature'},
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='basin',
        ),
        migrations.RemoveField(
            model_name='site',
            name='basin',
        ),
        migrations.AlterField(
            model_name='interval',
            name='average_conductivity',
            field=models.FloatField(blank=True, help_text='Reported thermal conductivity to accompany the heat flow estimate.', null=True, verbose_name='therm. cond.'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='conductivity_method',
            field=models.CharField(blank=True, help_text='Method used to measure or derive thermal conductivity.', max_length=150, null=True, verbose_name='cond. method'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='heat_production',
            field=models.FloatField(blank=True, help_text='Average heat production to accompany the heat flow estimate.', null=True, verbose_name='heat prod.'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='reliability',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('R', 'R'), ('Z', 'Z')], help_text='Heat flow reliability code', max_length=1, null=True, verbose_name='reliability'),
        ),
    ]
