# Generated by Django 3.0.8 on 2020-08-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0002_site_bottom_water_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='EOH_rock_type',
        ),
        migrations.RemoveField(
            model_name='site',
            name='USGS_code',
        ),
        migrations.RemoveField(
            model_name='site',
            name='site_status',
        ),
    ]
