# Generated by Django 3.2.12 on 2022-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0002_auto_20220316_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interval',
            old_name='conductivity_method',
            new_name='cond_method',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='conductivity_uncertainty',
            new_name='cond_unc',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='number_of_conductivities',
            new_name='num_cond',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='number_of_heat_gen',
            new_name='num_heat_prod',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='number_of_temperatures',
            new_name='num_temp',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='average_conductivity',
            new_name='cond_ave',
        ),
    ]
