# Generated by Django 3.1.1 on 2020-09-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0003_auto_20200914_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='thermoglobe.site', verbose_name='site'),
        ),
    ]
