# Generated by Django 3.0.8 on 2020-08-25 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0003_auto_20200825_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correction',
            old_name='has_bottom_water_variation',
            new_name='bottom_water_variation_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='has_climatic',
            new_name='climatic_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='has_compaction',
            new_name='compaction_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='has_fluid',
            new_name='fluid_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='has_other',
            new_name='other_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='has_refraction',
            new_name='refraction_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='has_sedimentation',
            new_name='sedimentation_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='has_topographic',
            new_name='topographic_flag',
        ),
        migrations.AlterField(
            model_name='correction',
            name='gradient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='thermoglobe.ThermalGradient'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='heatflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='thermoglobe.HeatFlow'),
        ),
        migrations.AlterField(
            model_name='heatflow',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_flow', to='thermoglobe.Site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='thermalgradient',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradients', to='thermoglobe.Site', verbose_name='site'),
        ),
    ]
