# Generated by Django 3.2.12 on 2022-03-08 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0003_auto_20220308_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmeta',
            name='depth',
        ),
    ]
