# Generated by Django 3.0.8 on 2020-08-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0004_auto_20200825_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='sediment_thickness_type',
            field=models.FloatField(blank=True, help_text='How sediment thickness was determined.', null=True, verbose_name='type of sediment thickness'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='bottom_water_variation',
            field=models.FloatField(blank=True, help_text='Value of a bottom_water_variation correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='bottom_water_variation_flag',
            field=models.BooleanField(default=False, verbose_name='bottom water variation flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='climatic',
            field=models.FloatField(blank=True, help_text='Value of a climatic correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='climatic_flag',
            field=models.BooleanField(default=False, verbose_name='climatic flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='compaction',
            field=models.FloatField(blank=True, help_text='Value of a compaction correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='compaction_flag',
            field=models.BooleanField(default=False, verbose_name='compaction flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='fluid',
            field=models.FloatField(blank=True, help_text='Value of a fluid correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='fluid_flag',
            field=models.BooleanField(default=False, verbose_name='fluid flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='other',
            field=models.FloatField(blank=True, help_text='Value of any other correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='other_flag',
            field=models.BooleanField(default=False, verbose_name='other flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='other_type',
            field=models.CharField(blank=True, help_text='Specifies the type of correction if the type does not belong to one of the other categories.', max_length=100, null=True, verbose_name='type of correction'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='refraction',
            field=models.FloatField(blank=True, help_text='Value of a refraction correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='refraction_flag',
            field=models.BooleanField(default=False, verbose_name='refraction flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='sedimentation',
            field=models.FloatField(blank=True, help_text='Value of a sedimentation correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='sedimentation_flag',
            field=models.BooleanField(default=False, verbose_name='sedimentation flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='topographic',
            field=models.FloatField(blank=True, help_text='Value of a topographic correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='topographic_flag',
            field=models.BooleanField(default=False, verbose_name='topographic flag'),
        ),
    ]
