# Generated by Django 3.2.12 on 2022-03-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0004_auto_20220316_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='cond_ave',
            field=models.FloatField(blank=True, help_text='Reported thermal conductivity to accompany the heat flow estimate.', null=True, verbose_name='conductivity'),
        ),
    ]
