# Generated by Django 3.1.1 on 2020-09-21 05:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0004_auto_20200916_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='is_bottom_of_hole',
        ),
        migrations.AddField(
            model_name='conductivity',
            name='formation',
            field=models.CharField(blank=True, help_text='The name of the sampled geological formation.', max_length=200, verbose_name='formation name'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='operator',
            field=models.CharField(blank=True, help_text='The operator collecting the measurements', max_length=150, null=True, verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='source_id',
            field=models.CharField(blank=True, help_text='This is the ID for the measurement used by the original source', max_length=150, null=True, verbose_name='source ID'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='formation',
            field=models.CharField(blank=True, help_text='The name of the sampled geological formation.', max_length=200, verbose_name='formation name'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='operator',
            field=models.CharField(blank=True, help_text='The operator collecting the measurements', max_length=150, null=True, verbose_name='operator'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='source_id',
            field=models.CharField(blank=True, help_text='This is the ID for the measurement used by the original source', max_length=150, null=True, verbose_name='source ID'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='circ_time',
            field=models.FloatField(blank=True, help_text='Circulation time in hours.', null=True, verbose_name='circulation time'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='correction',
            field=models.CharField(blank=True, help_text='Applied temperature correction type.', max_length=150, null=True, verbose_name='correction'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='formation',
            field=models.CharField(blank=True, help_text='The name of the sampled geological formation.', max_length=200, verbose_name='formation name'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='uncertainty',
            field=models.FloatField(blank=True, help_text='Uncertainty on the reported temperature.', null=True, verbose_name='uncertainty [&deg;C]'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='year_logged',
            field=models.PositiveIntegerField(blank=True, help_text='Year the temperature measurements were made.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year logged'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivities', to='thermoglobe.publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivities', to='thermoglobe.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='heatgeneration',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_gen', to='thermoglobe.publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='heatgeneration',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_gen', to='thermoglobe.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='depth',
            field=models.FloatField(blank=True, help_text='The depth at which the measurement was taken (if applicable).', null=True, verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='lag_time',
            field=models.FloatField(blank=True, help_text='Hours between drilling and measuring temperature.', null=True, verbose_name='lag time'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='method',
            field=models.CharField(blank=True, help_text='The method used to obtain the reported value.', max_length=200, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='thermoglobe.publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to='thermoglobe.site', verbose_name='site'),
        ),
    ]
