# Generated by Django 3.2.12 on 2022-03-16 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0005_alter_interval_cond_ave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interval',
            old_name='heat_production',
            new_name='heat_prod',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='heat_production_method',
            new_name='heat_prod_method',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='heat_production_uncertainty',
            new_name='heat_prod_unc',
        ),
        migrations.AlterField(
            model_name='interval',
            name='depth_max',
            field=models.FloatField(blank=True, help_text='Maximum depth of the measurement interval.', null=True, validators=[django.core.validators.MaxValueValidator(12500, 'Maximum depth may not exceed 12,500m.'), django.core.validators.MinValueValidator(0, 'Depth cannot be less than 0m.')], verbose_name='depth lower (m)'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='depth_min',
            field=models.FloatField(blank=True, help_text='Minimum depth of the measurement interval.', null=True, validators=[django.core.validators.MaxValueValidator(12500, 'Maximum depth may not exceed 12,500m.'), django.core.validators.MinValueValidator(0, 'Depth cannot be less than 0m.')], verbose_name='depth upper (m)'),
        ),
    ]
