# Generated by Django 3.1.1 on 2020-09-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0005_auto_20200921_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='log_id',
            field=models.CharField(blank=True, help_text='This is required so that multiple temperature logs can be stored on the same site.', max_length=64, null=True, verbose_name='ID of specific temperature log'),
        ),
    ]
