# Generated by Django 3.2.12 on 2022-03-08 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0005_delete_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='temperature (C)')),
                ('uncertainty', models.FloatField(blank=True, null=True, verbose_name='uncertainty')),
                ('depth', models.FloatField(verbose_name='depth (m)')),
                ('meta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='thermoglobe.tempmeta', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'temperature',
                'verbose_name_plural': 'temperature',
                'db_table': 'temperature',
                'ordering': ['depth'],
                'unique_together': {('temperature', 'depth', 'meta')},
            },
        ),
    ]
