# Generated by Django 3.0.8 on 2020-08-25 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0006_auto_20200825_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='ruggedness',
        ),
    ]
