# Generated by Django 3.1.1 on 2020-09-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0006_temperature_log_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('value', 'depth', 'site', 'log_id', 'reference')},
        ),
    ]
