# Generated by Django 3.2.13 on 2022-06-28 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0006_auto_20220316_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalSite',
        ),
    ]
