# Generated by Django 3.0.8 on 2020-08-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0007_remove_site_ruggedness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correction',
            old_name='climatic',
            new_name='climate',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='climatic_flag',
            new_name='climate_flag',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='sedimentation',
            new_name='sed_erosion',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='sedimentation_flag',
            new_name='sed_erosion_flag',
        ),
    ]
