# Generated by Django 3.1.1 on 2020-09-22 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0007_auto_20200921_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductivity',
            name='log_id',
            field=models.CharField(blank=True, help_text='This is required for multiple logs to be stored on the same site.', max_length=64, null=True, verbose_name='log specific ID'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='sample_diameter',
            field=models.FloatField(blank=True, help_text='Diameter of the sample.', null=True, verbose_name='sample_diameter'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='sample_length',
            field=models.FloatField(blank=True, help_text='Length of the sample.', null=True, verbose_name='sample_length'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='sample_thickness',
            field=models.FloatField(blank=True, help_text='Thickness of the sample.', null=True, verbose_name='sample_thickness'),
        ),
        migrations.AddField(
            model_name='conductivity',
            name='sample_width',
            field=models.FloatField(blank=True, help_text='Width of the sample.', null=True, verbose_name='sample_width'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='log_id',
            field=models.CharField(blank=True, help_text='This is required for multiple logs to be stored on the same site.', max_length=64, null=True, verbose_name='log specific ID'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivity', to='thermoglobe.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='heatgeneration',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_generation', to='thermoglobe.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='log_id',
            field=models.CharField(blank=True, help_text='This is required for multiple logs to be stored on the same site.', max_length=64, null=True, verbose_name='log specific ID'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='thermoglobe.site', verbose_name='site'),
        ),
    ]
