# Generated by Django 3.2.12 on 2022-03-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0007_auto_20220308_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='added'),
        ),
        migrations.CreateModel(
            name='NewCorrection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CLIM', 'Climate'), ('TOPO', 'Topographic'), ('REFR', 'Refraction'), ('FLUI', 'Fluid'), ('BWV', 'Bottom Water Variation'), ('EROS', 'Erosion'), ('COMP', 'Compaction'), ('OTH', 'Other')], max_length=4, verbose_name='correction type')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_corrections', to='thermoglobe.interval', verbose_name='interval')),
            ],
            options={
                'db_table': 'corrections',
            },
        ),
    ]
