# Generated by Django 3.0.8 on 2020-08-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0008_auto_20200826_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correction',
            name='bottom_water_variation_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='bottom water variation flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='climate_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='climate flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='compaction_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='compaction flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='fluid_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='fluid flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='other_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='other flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='refraction_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='refraction flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='sed_erosion_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='sedimentation flag'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='topographic_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='topographic flag'),
        ),
        migrations.AlterField(
            model_name='heatflow',
            name='global_flag',
            field=models.BooleanField(default=None, help_text='Measurement is suitable for use in global modelling.', null=True, verbose_name='global flag'),
        ),
    ]
