# Generated by Django 3.1.1 on 2020-09-22 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0008_auto_20200922_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductivity',
            name='year_logged',
            field=models.PositiveIntegerField(blank=True, help_text='Year the temperature measurements were made.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year logged'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='year_logged',
            field=models.PositiveIntegerField(blank=True, help_text='Year the temperature measurements were made.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year logged'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='sample_diameter',
            field=models.FloatField(blank=True, help_text='Diameter of the sample.', null=True, verbose_name='sample diameter'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='sample_length',
            field=models.FloatField(blank=True, help_text='Length of the sample.', null=True, verbose_name='sample length'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='sample_thickness',
            field=models.FloatField(blank=True, help_text='Thickness of the sample.', null=True, verbose_name='sample thickness'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='sample_width',
            field=models.FloatField(blank=True, help_text='Width of the sample.', null=True, verbose_name='sample width'),
        ),
    ]
