# Generated by Django 3.2.12 on 2022-03-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0008_auto_20220308_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Correction',
        ),
    ]
