# Generated by Django 3.0.8 on 2020-08-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0009_auto_20200826_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heatflow',
            old_name='corrected',
            new_name='heat_flow_corrected',
        ),
        migrations.RenameField(
            model_name='heatflow',
            old_name='corrected_uncertainty',
            new_name='heat_flow_corrected_unc',
        ),
        migrations.RenameField(
            model_name='heatflow',
            old_name='uncorrected',
            new_name='heat_flow_uncorrected',
        ),
        migrations.RenameField(
            model_name='heatflow',
            old_name='uncorrected_uncertainty',
            new_name='heat_flow_uncorrected_unc',
        ),
        migrations.RemoveField(
            model_name='correction',
            name='gradient',
        ),
        migrations.AddField(
            model_name='heatflow',
            name='gradient_cor',
            field=models.FloatField(blank=True, help_text='The corrected value.', null=True, verbose_name='corrected gradient [mW m<sup>2</sup>]'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='gradient_cor_unc',
            field=models.FloatField(blank=True, help_text='Uncertainty on the corrected value.', null=True, verbose_name='corrected uncertainty [mW m<sup>2</sup>]'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='gradient_uncor',
            field=models.FloatField(blank=True, help_text='The uncorrected value.', null=True, verbose_name='uncorrected gradient [mW m<sup>2</sup>]'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='gradient_uncor_uncertainty',
            field=models.FloatField(blank=True, help_text='Uncertainty on the uncorrected value.', null=True, verbose_name='uncorrected uncertainty [mW m<sup>2</sup>]'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='heat_gen',
            field=models.FloatField(blank=True, help_text='Average heat generation to accompany the heat flow estimate.', null=True, verbose_name='average heat generation'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='heat_gen_method',
            field=models.CharField(blank=True, help_text='Method used to measure or derive heat generation.', max_length=150, null=True, verbose_name='heat generation method'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='heat_gen_unc',
            field=models.FloatField(blank=True, help_text='Uncertainty of the reported heat generation.', null=True, verbose_name='heat generation uncertainty'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='num_heat_gen',
            field=models.FloatField(blank=True, help_text='Number of heat generation values from which the average heat generation was derived.', null=True, verbose_name='number of heat generation measurements'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='temp_method',
            field=models.CharField(blank=True, help_text='The method used to obtain temperature values.', max_length=200, verbose_name='temperature method'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='bottom_water_variation',
            field=models.FloatField(blank=True, help_text='Value of a bottom water variation correction applied to the associated heat flow and thermal gradient estimates.', null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='bottom_water_variation_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='BWV corrected'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='climate_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='climate corrected'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='compaction_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='compaction corrected'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='fluid_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='fluid corrected'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='other_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='other'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='refraction_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='refraction corrected'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='sed_erosion_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='sedimentation corrected'),
        ),
        migrations.AlterField(
            model_name='correction',
            name='topographic_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='topographic corrected'),
        ),
        migrations.DeleteModel(
            name='ThermalGradient',
        ),
    ]
