# Generated by Django 3.2.12 on 2022-03-08 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0009_delete_correction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewCorrection',
            new_name='Correction',
        ),
        migrations.AlterModelTable(
            name='correction',
            table='heat_flow_correction',
        ),
    ]
