# Generated by Django 3.1.1 on 2020-09-22 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0009_auto_20200922_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductivity',
            name='year_logged',
            field=models.PositiveIntegerField(blank=True, help_text='Year the measurement was made.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year logged'),
        ),
        migrations.AlterField(
            model_name='heatgeneration',
            name='year_logged',
            field=models.PositiveIntegerField(blank=True, help_text='Year the measurement was made.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year logged'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='year_logged',
            field=models.PositiveIntegerField(blank=True, help_text='Year the measurement was made.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year logged'),
        ),
        migrations.AlterUniqueTogether(
            name='conductivity',
            unique_together={('value', 'depth', 'site', 'log_id', 'reference')},
        ),
    ]
