# Generated by Django 3.1.1 on 2020-09-25 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0010_auto_20200922_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='depth_max',
            field=models.FloatField(blank=True, help_text='Maximum depth of the measurement interval.', null=True, validators=[django.core.validators.MaxValueValidator(12500, 'Maximum depth may not exceed 12,500m.'), django.core.validators.MinValueValidator(0, 'Depth cannot be less than 0m.')], verbose_name='depth max'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='depth_min',
            field=models.FloatField(blank=True, help_text='Minimum depth of the measurement interval.', null=True, validators=[django.core.validators.MaxValueValidator(12500, 'Maximum depth may not exceed 12,500m.'), django.core.validators.MinValueValidator(0, 'Depth cannot be less than 0m.')], verbose_name='depth min'),
        ),
    ]
