# Generated by Django 3.1.3 on 2020-11-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0012_auto_20200925_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='bottom_hole_temp',
        ),
        migrations.RemoveField(
            model_name='site',
            name='juvenile_age_max',
        ),
        migrations.RemoveField(
            model_name='site',
            name='juvenile_age_min',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tectonothermal_max',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tectonothermal_min',
        ),
        migrations.AlterField(
            model_name='interval',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='thermoglobe.publication', verbose_name='reference'),
        ),
    ]
