# Generated by Django 3.1.3 on 2020-11-09 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0013_auto_20201105_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='type',
            field=models.CharField(choices=[('C', 'continental'), ('O', 'oceanic')], default='C', max_length=1, verbose_name='site type'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivity', to='thermoglobe.publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='heatgeneration',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_generation', to='thermoglobe.publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publication or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature', to='thermoglobe.publication', verbose_name='reference'),
        ),
    ]
