# Generated by Django 3.1.3 on 2020-11-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0014_auto_20201109_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='type',
        ),
    ]
