# Generated by Django 3.1.3 on 2020-11-12 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0015_remove_site_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conductivity',
            old_name='value',
            new_name='conductivity',
        ),
        migrations.RenameField(
            model_name='heatgeneration',
            old_name='value',
            new_name='heat_generation',
        ),
        migrations.RenameField(
            model_name='temperature',
            old_name='value',
            new_name='temperature',
        ),
        migrations.AlterUniqueTogether(
            name='conductivity',
            unique_together={('conductivity', 'depth', 'site', 'log_id', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='heatgeneration',
            unique_together={('heat_generation', 'depth', 'site', 'reference')},
        ),
        migrations.AlterUniqueTogether(
            name='temperature',
            unique_together={('temperature', 'depth', 'site', 'log_id', 'reference')},
        ),
    ]
