# Generated by Django 3.1.3 on 2020-11-13 06:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0016_auto_20201112_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='site description'),
        ),
    ]
