# Generated by Django 3.1.3 on 2020-11-22 08:31

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0017_site_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('year'), descending=True, nulls_last=True), 'bib_id']},
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='conductivity',
            field=models.FloatField(help_text='The reported thermal conductivity in of the sample.', verbose_name='thermal conductivity'),
        ),
        migrations.AlterField(
            model_name='conductivity',
            name='uncertainty',
            field=models.FloatField(blank=True, help_text='The uncertainty on the reported value.', null=True, verbose_name='uncertainty'),
        ),
        migrations.AlterField(
            model_name='heatgeneration',
            name='heat_generation',
            field=models.FloatField(help_text='The reported value of the sample.', verbose_name='heat generation'),
        ),
        migrations.AlterField(
            model_name='heatgeneration',
            name='uncertainty',
            field=models.FloatField(blank=True, help_text='The uncertainty on the reported value.', null=True, verbose_name='uncertainty'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='gradient_corrected',
            field=models.FloatField(blank=True, help_text='The corrected value.', null=True, verbose_name='corrected gradient'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='gradient_corrected_uncertainty',
            field=models.FloatField(blank=True, help_text='Uncertainty on the corrected value.', null=True, verbose_name='corrected uncertainty'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='gradient_uncorrected',
            field=models.FloatField(blank=True, help_text='The uncorrected value.', null=True, verbose_name='uncorrected gradient'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='gradient_uncorrected_uncertainty',
            field=models.FloatField(blank=True, help_text='Uncertainty on the uncorrected value.', null=True, verbose_name='uncorrected uncertainty'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='heat_flow_corrected',
            field=models.FloatField(blank=True, help_text='The corrected value.', null=True, verbose_name='corrected heat flow'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='heat_flow_corrected_uncertainty',
            field=models.FloatField(blank=True, help_text='Uncertainty on the corrected value.', null=True, verbose_name='corrected uncertainty'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='heat_flow_uncorrected',
            field=models.FloatField(blank=True, help_text='The uncorrected value.', null=True, verbose_name='uncorrected heat flow'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='heat_flow_uncorrected_uncertainty',
            field=models.FloatField(blank=True, help_text='Uncertainty on the uncorrected value.', null=True, verbose_name='uncorrected uncertainty'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(help_text='The reported temperature in at the given depth.', verbose_name='temperature'),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='uncertainty',
            field=models.FloatField(blank=True, help_text='Uncertainty on the reported temperature.', null=True, verbose_name='uncertainty'),
        ),
    ]
