# Generated by Django 3.1.3 on 2020-11-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0019_custompublication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomPublication',
        ),
    ]
