# Generated by Django 3.1.3 on 2020-11-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0021_auto_20201123_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatgeneration',
            name='k_pc',
            field=models.FloatField(blank=True, null=True, verbose_name='K (wt%)'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='th_ppm',
            field=models.FloatField(blank=True, null=True, verbose_name='Th (ppm)'),
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='u_pp',
            field=models.FloatField(blank=True, null=True, verbose_name='U (ppm)'),
        ),
    ]
