# Generated by Django 3.1.3 on 2020-11-23 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0022_auto_20201123_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heatgeneration',
            old_name='u_pp',
            new_name='u_ppm',
        ),
    ]
