# Generated by Django 3.1.3 on 2020-11-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0023_auto_20201123_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='heatgeneration',
            unique_together={('log_id', 'heat_generation', 'k_pc', 'th_ppm', 'u_ppm', 'depth', 'site', 'reference')},
        ),
    ]
