# Generated by Django 3.1.3 on 2020-11-24 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0024_auto_20201123_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatgeneration',
            options={'verbose_name': 'heat generation', 'verbose_name_plural': 'heat generation'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': 'temperature', 'verbose_name_plural': 'temperature'},
        ),
    ]
