# Generated by Django 3.1.3 on 2020-11-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0025_auto_20201124_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='province',
        ),
    ]
