# Generated by Django 3.1.3 on 2020-11-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_province'),
        ('thermoglobe', '0026_remove_site_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='mapping.province', verbose_name='geological province'),
        ),
    ]
