# Generated by Django 3.1.3 on 2020-12-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0027_site_province'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heatgeneration',
            options={'default_related_name': 'heat_generation', 'verbose_name': 'heat generation', 'verbose_name_plural': 'heat generation'},
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['latitude'], name='site_latitud_652cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['longitude'], name='site_longitu_130adb_idx'),
        ),
    ]
