# Generated by Django 3.1.3 on 2020-12-01 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0028_auto_20201201_1201'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='site',
            name='site_latitud_652cf9_idx',
        ),
        migrations.RemoveIndex(
            model_name='site',
            name='site_longitu_130adb_idx',
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(db_index=True, help_text='Latitude in decimal degrees. WGS84 preferred but not enforced.', validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(-90)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(db_index=True, help_text='Longitude in decimal degrees. WGS84 preferred but not enforced.', validators=[django.core.validators.MaxValueValidator(180), django.core.validators.MinValueValidator(-180)], verbose_name='longitude'),
        ),
    ]
