# Generated by Django 3.1.3 on 2020-12-04 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0031_auto_20201203_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conductivity',
            name='age',
        ),
        migrations.RemoveField(
            model_name='conductivity',
            name='age_type',
        ),
        migrations.RemoveField(
            model_name='conductivity',
            name='rock_group',
        ),
        migrations.RemoveField(
            model_name='conductivity',
            name='rock_origin',
        ),
        migrations.RemoveField(
            model_name='heatgeneration',
            name='age',
        ),
        migrations.RemoveField(
            model_name='heatgeneration',
            name='age_type',
        ),
        migrations.RemoveField(
            model_name='heatgeneration',
            name='rock_group',
        ),
        migrations.RemoveField(
            model_name='heatgeneration',
            name='rock_origin',
        ),
        migrations.RemoveField(
            model_name='heatgeneration',
            name='sample_name',
        ),
    ]
