# Generated by Django 3.1.3 on 2020-12-04 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0032_auto_20201204_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correction',
            old_name='bottom_water_variation',
            new_name='bwv',
        ),
        migrations.RenameField(
            model_name='correction',
            old_name='bottom_water_variation_flag',
            new_name='bwv_flag',
        ),
    ]
