# Generated by Django 3.1.3 on 2020-12-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0033_auto_20201204_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='global_flag',
            field=models.BooleanField(default=False, help_text='Measurement is suitable for use in global modelling.', null=True, verbose_name='global flag'),
        ),
    ]
