# Generated by Django 3.1.3 on 2020-12-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0034_auto_20201209_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsite',
            name='bottom_water_temp',
        ),
        migrations.RemoveField(
            model_name='historicalsite',
            name='surface_temp',
        ),
        migrations.RemoveField(
            model_name='site',
            name='bottom_water_temp',
        ),
        migrations.RemoveField(
            model_name='site',
            name='surface_temp',
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='bwt',
            field=models.FloatField(blank=True, help_text='Temperature at the bottom of the water column.', null=True, verbose_name='bottom_water_temperature'),
        ),
        migrations.AddField(
            model_name='site',
            name='bwt',
            field=models.FloatField(blank=True, help_text='Temperature at the bottom of the water column.', null=True, verbose_name='bottom_water_temperature'),
        ),
    ]
