# Generated by Django 3.1.3 on 2020-12-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0035_auto_20201210_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsite',
            old_name='bwt',
            new_name='bottom_water_temp',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='bwt',
            new_name='bottom_water_temp',
        ),
    ]
