# Generated by Django 3.1.3 on 2020-12-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0036_auto_20201210_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProxy',
            fields=[
            ],
            options={
                'verbose_name': 'IngredientColourRelation (Exports Metadata)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('thermoglobe.site',),
        ),
    ]
