# Generated by Django 3.1.3 on 2020-12-15 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0037_siteproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteProxy',
        ),
    ]
