# Generated by Django 3.1.3 on 2020-12-15 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0039_auto_20201215_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conductivity',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heatgeneration',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpublication',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsite',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interval',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date added to ThermoGlobe'),
            preserve_default=False,
        ),
    ]
