# Generated by Django 2.2.24 on 2021-10-22 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='external',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='thumbnail',
        ),
    ]
