# Generated by Django 2.2.24 on 2021-10-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20211026_2356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='authors',
            new_name='author',
        ),
    ]
