# Generated by Django 2.2.24 on 2021-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20211027_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='issn',
            field=models.CharField(blank=True, help_text='For journals.', max_length=32, verbose_name='ISSN'),
        ),
    ]
