# Generated by Django 2.2.24 on 2021-10-27 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_issn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-year', 'citekey'], 'verbose_name_plural': ' Publications'},
        ),
        migrations.RemoveField(
            model_name='publication',
            name='book_title',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='code',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='issn',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='lists',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='month',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='note',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='number',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='volume',
        ),
    ]
