# Generated by Django 2.2.24 on 2021-10-27 00:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('publications', '0007_auto_20211027_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='keywords',
        ),
        migrations.AddField(
            model_name='publication',
            name='keywords',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
