# Generated by Django 2.2.24 on 2021-10-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20211027_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='type',
            new_name='ENTRYTYPE',
        ),
    ]
