# Generated by Django 2.2.24 on 2021-10-27 11:27

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20211027_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('year'), descending=True, nulls_last=True), 'citekey'], 'verbose_name_plural': ' Publications'},
        ),
    ]
