# Generated by Django 2.2.24 on 2021-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20211027_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bibtex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
