# Generated by Django 5.1.6 on 2025-06-20 13:40

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager

import django_lifecycle.mixins
import partial_date.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dataset", "0002_initial"),
        ("literature", "0004_alter_literatureitem_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this record was added to the database.",
                        verbose_name="Date added",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified.",
                        verbose_name="Last modified",
                    ),
                ),
                (
                    "start_date",
                    partial_date.fields.PartialDateField(
                        blank=True,
                        help_text="Date the review was started.",
                        null=True,
                        verbose_name="start date",
                    ),
                ),
                (
                    "end_date",
                    partial_date.fields.PartialDateField(
                        blank=True,
                        help_text="Date the review was completed.",
                        null=True,
                        verbose_name="completion date",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Open to review"),
                            (1, "Pending"),
                            (2, "Complete"),
                        ],
                        default=1,
                        help_text="The status of the review.",
                        verbose_name="status",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="General comment on the review.",
                        null=True,
                        verbose_name="comment",
                    ),
                ),
                (
                    "dataset",
                    auto_prefetch.OneToOneField(
                        help_text="The dataset that was reviewed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="dataset.dataset",
                        verbose_name="dataset",
                    ),
                ),
                (
                    "literature",
                    auto_prefetch.OneToOneField(
                        help_text="The literature item that was reviewed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="literature.literatureitem",
                        verbose_name="literature",
                    ),
                ),
                (
                    "reviewers",
                    models.ManyToManyField(
                        help_text="Users who have reviewed the data.",
                        related_name="heat_flow_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-end_date"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
