# Generated by Django 5.2.17 on 2026-09-15 20:11, hand-edited (T006):
# ``state`` must exist before ``status`` is read for the last time and
# removed, and the two are bridged by a data migration in between rather
# than kept side by side, per data-model.md's "existing status field is
# migrated into state rather than kept alongside".

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Old Review.STATUS_CHOICES -> new review.states.States:
#   OPEN (0)     -> DESCRIBED (0): not yet reviewed reads as not yet described.
#   PENDING (1)  -> AWAITING_DECISION (1): the closest existing analogue of
#                   "waiting on something" in the new vocabulary.
#   COMPLETE (2) -> COMPLETE (3): unchanged in meaning.
STATUS_TO_STATE = {0: 0, 1: 1, 2: 3}


def migrate_status_into_state(apps, schema_editor):
    Review = apps.get_model("review", "Review")
    for old_value, new_value in STATUS_TO_STATE.items():
        Review.objects.filter(status=old_value).update(state=new_value)


def migrate_state_into_status(apps, schema_editor):
    """Reverse of ``migrate_status_into_state``, for unapplying this
    migration. Runs while both fields still exist, after ``status`` has
    been re-added by the reverse of the ``RemoveField`` below."""
    Review = apps.get_model("review", "Review")
    for old_value, new_value in STATUS_TO_STATE.items():
        Review.objects.filter(state=new_value).update(status=old_value)


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_data_assessor_and_data_curator_groups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="state",
            field=models.IntegerField(
                choices=[
                    (0, "Described"),
                    (1, "Awaiting decision"),
                    (2, "Changes requested"),
                    (3, "Complete"),
                ],
                default=0,
                help_text="Where this assessment has got to.",
                verbose_name="state",
            ),
        ),
        migrations.RunPython(migrate_status_into_state, migrate_state_into_status),
        migrations.RemoveField(
            model_name="review",
            name="status",
        ),
        migrations.AddField(
            model_name="review",
            name="decided_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the decision on this assessment was made.",
                null=True,
                verbose_name="decided at",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="decided_by",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="The Data Curator who approved or sent back this assessment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="decided by",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="decision_comment",
            field=models.TextField(
                blank=True,
                help_text="What the curator said when sending this assessment back.",
                verbose_name="decision comment",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="uploaded_by",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text=(
                    "The person who created this assessment. Object permissions "
                    "follow this person rather than the assessor list, because an "
                    "assessor may be an unclaimed profile with no account."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
    ]
