# Generated by Django 5.2.17 on 2026-09-15 20:16

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
import review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_workflow_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True, help_text='The date and time this record was added to the database.', verbose_name='Date added')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date and time this record was last modified.', verbose_name='Last modified')),
                ('file', models.FileField(help_text='The completed upload template as supplied.', upload_to=review.models.submission_upload_path, verbose_name='file')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this file was submitted.', verbose_name='submitted at')),
                ('imported_at', models.DateTimeField(blank=True, help_text="When this file's contents were written. Null means checked but never confirmed.", null=True, verbose_name='imported at')),
                ('review', auto_prefetch.ForeignKey(help_text='The assessment this file was submitted against.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='review.review', verbose_name='assessment')),
                ('submitted_by', auto_prefetch.ForeignKey(help_text='Who submitted this file.', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_files', to=settings.AUTH_USER_MODEL, verbose_name='submitted by')),
            ],
            options={
                'verbose_name': 'Submitted file',
                'verbose_name_plural': 'Submitted files',
                'ordering': ['-submitted_at'],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
