# Generated by Django 5.2.17 on 2026-09-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_submitted_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-end_date'], 'verbose_name': 'Assessment', 'verbose_name_plural': 'Assessments'},
        ),
    ]
