# Generated by Django 3.2.9 on 2021-11-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0003_auto_20211105_1331'),
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basin',
        ),
    ]
