# Generated by Django 3.1.1 on 2020-09-25 03:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(max_length=80)),
                ('reference', models.CharField(max_length=80)),
                ('group', models.CharField(max_length=80)),
                ('juvenile_age_min', models.FloatField()),
                ('juvenile_age_max', models.FloatField()),
                ('tectonic_age_min', models.FloatField()),
                ('tectonic_age_max', models.FloatField()),
                ('last_orogen', models.CharField(max_length=80)),
                ('continent', models.CharField(max_length=80)),
                ('plate', models.CharField(max_length=80)),
                ('juvenile_age_ref', models.CharField(max_length=128)),
                ('tectonic_age_ref', models.CharField(max_length=128)),
                ('area_km2', models.BigIntegerField()),
                ('conjugate_province', models.CharField(max_length=128)),
                ('comments', models.CharField(max_length=254)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
