# Generated by Django 3.2.11 on 2022-02-01 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_delete_basin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='area',
        ),
        migrations.RemoveField(
            model_name='country',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='country',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='country',
            name='pop2005',
        ),
        migrations.RemoveField(
            model_name='country',
            name='un',
        ),
    ]
