# Generated by Django 3.2.12 on 2022-02-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0002_auto_20220211_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='political',
            name='changes',
        ),
    ]
