# Generated by Django 3.2.15 on 2022-08-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20220823_1637'),
        ('database', '0034_auto_20220823_1637'),
        ('mapping', '0002_auto_20220823_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
