# Generated by Django 3.2.12 on 2022-02-11 08:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0003_remove_political_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('name', models.CharField(max_length=254)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4236)),
            ],
            options={
                'verbose_name': 'Ocean/Sea',
                'verbose_name_plural': 'Oceans/Seas',
                'db_table': 'global_oceans',
            },
        ),
    ]
