# Generated by Django 3.2.12 on 2022-02-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0002_auto_20220211_1956'),
        ('mapping', '0004_ocean'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sea',
        ),
    ]
