# Generated by Django 3.2.11 on 2022-02-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0004_auto_20220201_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GISPackage',
        ),
    ]
