# Generated by Django 3.1.3 on 2020-11-25 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0026_remove_site_province'),
        ('mapping', '0005_province'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
