# Generated by Django 3.2.12 on 2022-02-11 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0005_delete_sea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('plate_id', models.IntegerField()),
                ('plate', models.CharField(max_length=128)),
                ('subplate', models.CharField(max_length=128)),
                ('poly_name', models.CharField(max_length=100)),
                ('plate_type', models.CharField(max_length=64)),
                ('crust_type', models.CharField(choices=[('continental', 'continental'), ('oceanic', 'oceanic')], max_length=12)),
                ('domain', models.CharField(blank=True, max_length=64, null=True)),
                ('references', models.CharField(blank=True, max_length=100, null=True)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4236)),
            ],
            options={
                'verbose_name': 'tectonic plate',
                'verbose_name_plural': 'tectonic plates',
                'db_table': 'tectonic_plates',
            },
        ),
    ]
