# Generated by Django 3.2.12 on 2022-02-11 11:09

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plate',
            old_name='subplate',
            new_name='name',
        ),
        migrations.AddField(
            model_name='plate',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
