# Generated by Django 3.1.3 on 2020-11-25 07:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0006_delete_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('group', models.CharField(blank=True, max_length=80, null=True)),
                ('juvenile_age_min', models.FloatField(blank=True, null=True)),
                ('juvenile_age_max', models.FloatField(blank=True, null=True)),
                ('tectonic_age_min', models.FloatField(blank=True, null=True)),
                ('tectonic_age_max', models.FloatField(blank=True, null=True)),
                ('last_orogen', models.CharField(blank=True, max_length=80, null=True)),
                ('continent', models.CharField(blank=True, max_length=80, null=True)),
                ('plate', models.CharField(blank=True, max_length=80, null=True)),
                ('juvenile_age_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('tectonic_age_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('area_km2', models.BigIntegerField(blank=True, null=True)),
                ('conjugate_province', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.CharField(blank=True, max_length=254, null=True)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'geological_province',
            },
        ),
    ]
