# Generated by Django 3.2.12 on 2022-02-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_auto_20220211_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='conjugate_province',
        ),
        migrations.RemoveField(
            model_name='province',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='province',
            name='juvenile_age_max',
        ),
        migrations.RemoveField(
            model_name='province',
            name='juvenile_age_min',
        ),
        migrations.RemoveField(
            model_name='province',
            name='juvenile_age_ref',
        ),
        migrations.RemoveField(
            model_name='province',
            name='plate',
        ),
        migrations.RemoveField(
            model_name='province',
            name='source_id',
        ),
        migrations.RemoveField(
            model_name='province',
            name='thermotectonic_age_max',
        ),
        migrations.RemoveField(
            model_name='province',
            name='thermotectonic_age_min',
        ),
        migrations.RemoveField(
            model_name='province',
            name='thermotectonic_age_ref',
        ),
        migrations.AddField(
            model_name='province',
            name='crust_type',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='group',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='last_orogen',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='reference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
