# Generated by Django 3.1.3 on 2020-11-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0007_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='tectonic_age_max',
            new_name='thermotectonic_age_max',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='tectonic_age_min',
            new_name='thermotectonic_age_min',
        ),
        migrations.RenameField(
            model_name='province',
            old_name='tectonic_age_ref',
            new_name='thermotectonic_age_ref',
        ),
    ]
