# Generated by Django 3.1.3 on 2020-11-28 13:31

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0008_auto_20201126_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basin',
            options={'verbose_name': 'Sedimentary Basin', 'verbose_name_plural': 'Sedimentary Basins'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'continent', 'verbose_name_plural': 'continents'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='political',
            options={'verbose_name': 'Political Region', 'verbose_name_plural': 'Political Regions'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'Geological Province', 'verbose_name_plural': 'Geological Provinces'},
        ),
        migrations.AlterModelOptions(
            name='sea',
            options={'ordering': ['name'], 'verbose_name': 'Sea/Ocean', 'verbose_name_plural': 'Seas/Oceans'},
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
