# Generated by Django 3.1.3 on 2020-12-01 01:31

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0010_auto_20201129_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='margin',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name'),
        ),
    ]
