# Generated by Django 3.2.12 on 2022-02-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0011_alter_plate_crust_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='crust_type',
            field=models.CharField(choices=[('C', 'Continental'), ('O', 'Oceanic')], max_length=1),
        ),
    ]
