# Generated by Django 3.1.3 on 2020-12-14 08:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0012_auto_20201214_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='raster name')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(srid=4326, verbose_name='raster image')),
            ],
            options={
                'db_table': 'rasters',
            },
        ),
    ]
