# Generated by Django 3.2.14 on 2022-07-08 15:08

import core.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publications', '0001_initial'),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureLog',
            fields=[
                ('method', models.CharField(blank=True, max_length=200, null=True, verbose_name='method')),
                ('operator', models.CharField(blank=True, help_text='The operator collecting the measurements', max_length=150, null=True, verbose_name='operator')),
                ('source', models.CharField(blank=True, help_text='Where the data came from', max_length=50, null=True, verbose_name='original source')),
                ('source_id', models.CharField(blank=True, help_text='ID from data source', max_length=64, null=True, verbose_name='original source ID')),
                ('year_logged', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', length=10, max_length=15, prefix='GHFLOG-T', primary_key=True, serialize=False)),
                ('circ_time', models.FloatField(blank=True, null=True, verbose_name='circulation time (hrs)')),
                ('lag_time', models.FloatField(blank=True, null=True, verbose_name='lag time (hrs)')),
                ('correction', models.CharField(blank=True, max_length=150, null=True, verbose_name='correction type')),
                ('reference', models.ForeignKey(blank=True, help_text='The publications or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='publications.publication', verbose_name='reference')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='database.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'temperature',
                'verbose_name_plural': 'temperature',
                'db_table': 'temp_meta',
                'ordering': ['added'],
                'default_related_name': 'temperature_logs',
            },
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', core.fields.RangeField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(-273.15)], verbose_name='temperature')),
                ('uncertainty', core.fields.RangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='uncertainty')),
                ('depth', core.fields.RangeField(validators=[django.core.validators.MaxValueValidator(13000), django.core.validators.MinValueValidator(0)], verbose_name='depth (m)')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='well_logs.temperaturelog', verbose_name='log')),
            ],
            options={
                'verbose_name': 'temperature data',
                'verbose_name_plural': 'temperature data',
                'db_table': 'temperature',
            },
        ),
        migrations.CreateModel(
            name='HeatProductionLog',
            fields=[
                ('method', models.CharField(blank=True, max_length=200, null=True, verbose_name='method')),
                ('operator', models.CharField(blank=True, help_text='The operator collecting the measurements', max_length=150, null=True, verbose_name='operator')),
                ('source', models.CharField(blank=True, help_text='Where the data came from', max_length=50, null=True, verbose_name='original source')),
                ('source_id', models.CharField(blank=True, help_text='ID from data source', max_length=64, null=True, verbose_name='original source ID')),
                ('year_logged', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', length=10, max_length=15, prefix='GHFLOG-HP', primary_key=True, serialize=False)),
                ('reference', models.ForeignKey(blank=True, help_text='The publications or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_production_logs', to='publications.publication', verbose_name='reference')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_production_logs', to='database.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'heat production',
                'verbose_name_plural': 'heat production',
                'db_table': 'heat_production_log',
                'default_related_name': 'heat_production_logs',
            },
        ),
        migrations.CreateModel(
            name='HeatProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncertainty', models.FloatField(blank=True, null=True, verbose_name='uncertainty')),
                ('depth', models.FloatField(verbose_name='depth (m)')),
                ('rock_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='rock type')),
                ('k_pc', models.FloatField(blank=True, null=True, verbose_name='K (wt%)')),
                ('th_ppm', models.FloatField(blank=True, null=True, verbose_name='Th (ppm)')),
                ('u_ppm', models.FloatField(blank=True, null=True, verbose_name='U (ppm)')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='well_logs.heatproductionlog', verbose_name='log')),
            ],
            options={
                'db_table': 'heat_production',
            },
        ),
        migrations.CreateModel(
            name='ConductivityLog',
            fields=[
                ('method', models.CharField(blank=True, max_length=200, null=True, verbose_name='method')),
                ('operator', models.CharField(blank=True, help_text='The operator collecting the measurements', max_length=150, null=True, verbose_name='operator')),
                ('source', models.CharField(blank=True, help_text='Where the data came from', max_length=50, null=True, verbose_name='original source')),
                ('source_id', models.CharField(blank=True, help_text='ID from data source', max_length=64, null=True, verbose_name='original source ID')),
                ('year_logged', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='added')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet='23456789ABCDEFGHJKLMNPQRSTUVWXYZ', length=10, max_length=15, prefix='GHFLOG-TC', primary_key=True, serialize=False)),
                ('reference', models.ForeignKey(blank=True, help_text='The publications or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivity_logs', to='publications.publication', verbose_name='reference')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivity_logs', to='database.site', verbose_name='site')),
            ],
            options={
                'verbose_name': 'thermal conductivity',
                'verbose_name_plural': 'thermal conductivity',
                'db_table': 'thermal_conductivity_log',
                'default_related_name': 'conductivity_logs',
            },
        ),
        migrations.CreateModel(
            name='Conductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', core.fields.RangeField(validators=[django.core.validators.MaxValueValidator(99.9), django.core.validators.MinValueValidator(0)], verbose_name='thermal conductivity')),
                ('uncertainty', core.fields.RangeField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='uncertainty')),
                ('depth', core.fields.RangeField(validators=[django.core.validators.MaxValueValidator(13000), django.core.validators.MinValueValidator(0)], verbose_name='depth (m)')),
                ('sample_type', models.CharField(choices=[('outcrop', 'Outcrop samples'), ('core', 'Core samples'), ('cuttings', 'Cutting samples'), ('mineral_comp', 'Mineral computation'), ('well_log_interp', 'Well log interpretation'), ('core_log_integration', 'Core-log integration'), ('insitu_probe', 'In-situ probe'), ('other', 'Other (specify in comments field)'), ('not_specified', 'Not specified')], help_text='Type of sample used to determine conductivity', max_length=20, verbose_name='sample_type')),
                ('method', models.CharField(blank=True, help_text='Method used to determine the mean thermal conductivity over the given interval', max_length=100, null=True, verbose_name='thermal conductivity method')),
                ('saturation_state', models.CharField(help_text='Saturation state of the sample', max_length=100, verbose_name='thermal conductivity saturation')),
                ('lithology', models.CharField(blank=True, help_text='Dominant rock type/lithology within the interval of heat-flow determination. Use existing BGS rock classification scheme for naming the lithology.', max_length=255, null=True, verbose_name='lithology')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='sample name/ID')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='length (cm)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='width (cm)')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='diameter (cm)')),
                ('thickness', models.FloatField(blank=True, null=True, verbose_name='thickness (cm)')),
                ('orientation', core.fields.RangeField(blank=True, help_text='Angle relative to the foliation/bedding where 0 is parallel and 90 is perpendicular', null=True, validators=[django.core.validators.MaxValueValidator(90), django.core.validators.MinValueValidator(0)], verbose_name='orientation')),
                ('IGSN', models.CharField(help_text='International Geo Sample Numbers (IGSN, semicolon separated) for rock samples used for laboratory measurements of thermal conductivity', max_length=100, verbose_name='IGSN sample number')),
                ('log', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='well_logs.conductivitylog', verbose_name='log')),
            ],
            options={
                'db_table': 'thermal_conductivity',
                'ordering': ['depth'],
                'unique_together': {('value', 'depth', 'log')},
            },
        ),
    ]
