# Generated by Django 3.2.14 on 2022-07-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductivity',
            name='sample_type',
            field=models.CharField(choices=[('outcrop samples', 'Outcrop samples'), ('core samples', 'Core samples'), ('cutting samples', 'Cutting samples'), ('mineral computation', 'Mineral computation'), ('well log interpretation', 'Well log interpretation'), ('core-log integration', 'Core-log integration'), ('in-situ probe', 'In-situ probe'), ('other', 'Other (specify in comments field)'), ('unspecified', 'Unspecified')], help_text='Type of sample used to determine conductivity', max_length=23, verbose_name='sample_type'),
        ),
    ]
