# Generated by Django 3.2.12 on 2022-03-08 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductivity',
            options={'ordering': ['depth']},
        ),
        migrations.AlterModelOptions(
            name='conductivitylog',
            options={'default_related_name': 'conductivity', 'verbose_name': 'thermal conductivity', 'verbose_name_plural': 'thermal conductivity'},
        ),
        migrations.AlterModelOptions(
            name='heatproduction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='heatproductionlog',
            options={'default_related_name': 'heat_production', 'verbose_name': 'heat production', 'verbose_name_plural': 'heat production'},
        ),
        migrations.AlterModelOptions(
            name='temperature',
            options={'verbose_name': 'temperature data', 'verbose_name_plural': 'temperature data'},
        ),
        migrations.AlterModelOptions(
            name='temperaturelog',
            options={'default_related_name': 'temperature', 'verbose_name': 'temperature', 'verbose_name_plural': 'temperature'},
        ),
        migrations.AlterField(
            model_name='conductivitylog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='conductivitylog',
            name='formation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='geological formation'),
        ),
        migrations.AlterField(
            model_name='conductivitylog',
            name='method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='conductivitylog',
            name='year_logged',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='heatproductionlog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='heatproductionlog',
            name='formation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='geological formation'),
        ),
        migrations.AlterField(
            model_name='heatproductionlog',
            name='method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='heatproductionlog',
            name='year_logged',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='circ_time',
            field=models.FloatField(blank=True, null=True, verbose_name='circulation time (hrs)'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='correction',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='correction type'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='formation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='geological formation'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='lag_time',
            field=models.FloatField(blank=True, null=True, verbose_name='lag time (hrs)'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='method',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='method'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='year_logged',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)], verbose_name='year'),
        ),
    ]
