# Generated by Django 3.2.12 on 2022-03-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thermoglobe', '0002_auto_20220316_1745'),
        ('publications', '0001_initial'),
        ('well_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductivitylog',
            options={'default_related_name': 'conductivity_logs', 'verbose_name': 'thermal conductivity', 'verbose_name_plural': 'thermal conductivity'},
        ),
        migrations.AlterModelOptions(
            name='heatproductionlog',
            options={'default_related_name': 'heat_production_logs', 'verbose_name': 'heat production', 'verbose_name_plural': 'heat production'},
        ),
        migrations.AlterModelOptions(
            name='temperaturelog',
            options={'default_related_name': 'temperature_logs', 'ordering': ['added'], 'verbose_name': 'temperature', 'verbose_name_plural': 'temperature'},
        ),
        migrations.AlterField(
            model_name='conductivitylog',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publications or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivity_logs', to='publications.Publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='conductivitylog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductivity_logs', to='thermoglobe.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='heatproductionlog',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publications or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_production_logs', to='publications.Publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='heatproductionlog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heat_production_logs', to='thermoglobe.site', verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='The publications or other reference from which the measurement was reported.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='publications.Publication', verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='temperaturelog',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature_logs', to='thermoglobe.site', verbose_name='site'),
        ),
    ]
