# Generated by Django 3.2.15 on 2022-08-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('well_logs', '0003_auto_20220805_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temperaturelog',
            options={'default_related_name': 'temperature_logs', 'ordering': ['date_added'], 'verbose_name': 'temperature', 'verbose_name_plural': 'temperature'},
        ),
        migrations.RenameField(
            model_name='conductivitylog',
            old_name='added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='heatproductionlog',
            old_name='added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='temperaturelog',
            old_name='added',
            new_name='date_added',
        ),
    ]
