# Generated by Django 5.1.6 on 2025-07-03 19:29

import fairdm.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heat_flow", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heatflow",
            name="date_acquired",
            field=fairdm.db.fields.PartialDateField(
                blank=True,
                help_text="Year of acquisition of the heat-flow data which may differ from publication year. Must be in YYYY-MM-DD format. Note: DD is optional.",
                null=True,
                verbose_name="date of acquisition ",
            ),
        ),
        migrations.AlterField(
            model_name="heatflowinterval",
            name="vertical_datum",
            field=models.CharField(
                choices=[("MSL", "Mean Sea Level")],
                default="MSL",
                help_text="The vertical datum used to determine depth measurements.",
                max_length=255,
                verbose_name="vertical datum",
            ),
        ),
        migrations.AlterField(
            model_name="heatflowinterval",
            name="vertical_depth",
            field=fairdm.db.fields.QuantityField(
                base_units="m",
                blank=True,
                help_text="The total depth of the vertical interval, calculated as the absolute difference between the interval top and interval bottom.",
                null=True,
                unit_choices=["m"],
                verbose_name="vertical depth",
            ),
        ),
        migrations.AlterField(
            model_name="heatflowsite",
            name="vertical_datum",
            field=models.CharField(
                choices=[("MSL", "Mean Sea Level")],
                default="MSL",
                help_text="The vertical datum used to determine depth measurements.",
                max_length=255,
                verbose_name="vertical datum",
            ),
        ),
        migrations.AlterField(
            model_name="heatflowsite",
            name="vertical_depth",
            field=fairdm.db.fields.QuantityField(
                base_units="m",
                blank=True,
                help_text="The total depth of the vertical interval, calculated as the absolute difference between the interval top and interval bottom.",
                null=True,
                unit_choices=["m"],
                verbose_name="vertical depth",
            ),
        ),
    ]
