# Generated by Django 5.2.5 on 2025-08-25 15:24

import heat_flow.vocabularies
import research_vocabs.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heat_flow", "0003_heatflow_m_score_heatflow_u_score_and_more"),
        ("measurement", "0003_alter_measurement_options"),
        ("research_vocabs", "0002_alter_concept_unique_together"),
        ("sample", "0002_alter_sample_options"),
        ("stratigraphy", "0002_alter_stratigraphicunit_genesis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heatflow",
            name="corr_PAL_flag",
            field=research_vocabs.fields.ConceptField(
                blank=True,
                default="unspecified",
                help_text="Specifies if paleoclimatic effects with respect to the reported heat-flow value were present and if corrections were performed.",
                max_length=23,
                null=True,
                verbose_name="Correction (PAL)",
                vocabulary=heat_flow.vocabularies.GenericFlagChoices,
            ),
        ),
        migrations.AddIndex(
            model_name="heatflow",
            index=models.Index(
                fields=["relevant_child"], name="heat_flow_h_relevan_4eb3f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heatflow",
            index=models.Index(
                fields=["U_score"], name="heat_flow_h_U_score_6332e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heatflow",
            index=models.Index(
                fields=["M_score"], name="heat_flow_h_M_score_0437ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heatflowsite",
            index=models.Index(
                fields=["country"], name="heat_flow_h_country_f7a8a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heatflowsite",
            index=models.Index(
                fields=["continent"], name="heat_flow_h_contine_e87180_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heatflowsite",
            index=models.Index(
                fields=["environment"], name="heat_flow_h_environ_2e87f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intervalconductivity",
            index=models.Index(fields=["number"], name="heat_flow_i_number_c3fed0_idx"),
        ),
        migrations.AddIndex(
            model_name="surfaceheatflow",
            index=models.Index(
                fields=["is_ghfdb"], name="heat_flow_s_is_ghfd_cfae5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="surfaceheatflow",
            index=models.Index(
                fields=["corr_HP_flag"], name="heat_flow_s_corr_HP_48836a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thermalgradient",
            index=models.Index(fields=["score"], name="heat_flow_t_score_e7b300_idx"),
        ),
        migrations.AddIndex(
            model_name="thermalgradient",
            index=models.Index(fields=["number"], name="heat_flow_t_number_a24ec2_idx"),
        ),
        migrations.AddConstraint(
            model_name="thermalgradient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("number__gt", 0), ("number__isnull", True), _connector="OR"
                ),
                name="positive_temperature_recordings",
            ),
        ),
    ]
