# Generated by Django 5.2.5 on 2026-04-08 12:24

import auto_prefetch
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django_lifecycle.mixins
import fairdm.db.fields
import heat_flow.vocabularies
import research_vocabs.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heat_flow", "0004_alter_heatflow_corr_pal_flag_and_more"),
        ("measurement", "0007_alter_measurementdate_type_and_more"),
        ("research_vocabs", "0002_alter_concept_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="GHFDBRelease",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "added",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time this record was added to the database.",
                        verbose_name="Date added",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time this record was last modified.",
                        verbose_name="Last modified",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True, verbose_name="Version")),
                ("release_date", models.DateField(verbose_name="Release Date")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("file", models.FileField(upload_to="ghfdb/releases/", verbose_name="Release File")),
            ],
            options={
                "verbose_name": "GHFDB Release",
                "verbose_name_plural": "GHFDB Releases",
                "db_table": "ghfdb_ghfdbrelease",
                "ordering": ["-release_date"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HeatFlowCorrection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "correction_type",
                    models.CharField(
                        choices=[
                            ("IS", "In-situ conditions"),
                            ("T", "Temperature"),
                            ("S", "Sedimentation/Subsidence"),
                            ("E", "Erosion"),
                            ("TOPO", "Topographic"),
                            ("PAL", "Paleoclimatic"),
                            ("SUR", "Surface/Climatic"),
                            ("CONV", "Convection"),
                            ("HR", "Heat Refraction"),
                        ],
                        help_text="Type of correction applied to the heat flow measurement.",
                        max_length=10,
                        verbose_name="correction type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present_corrected", "Present and corrected"),
                            ("present_not_corrected", "Present and not corrected"),
                            ("present_not_significant", "Present not significant"),
                            ("not_recognized", "not recognized"),
                            ("considered_p", "Considered - p"),
                            ("considered_t", "Considered - t"),
                            ("considered_pt", "Considered - pT"),
                            ("not_considered", "not considered"),
                            ("tilt_corrected", "Tilt corrected"),
                            ("drift_corrected", "Drift corrected"),
                            ("not_corrected", "not corrected"),
                            ("corrected", "Corrected"),
                            ("-", "unspecified"),
                        ],
                        default="-",
                        help_text="Whether the correction was present and applied.",
                        max_length=25,
                        verbose_name="correction status",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Comment regarding the applied correction.",
                        null=True,
                        verbose_name="comment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Heat Flow Correction",
                "verbose_name_plural": "Heat Flow Corrections",
                "db_table_comment": "Corrections applied to heat flow measurements",
            },
        ),
        migrations.CreateModel(
            name="ParentHeatFlow",
            fields=[
                (
                    "measurement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="measurement.measurement",
                    ),
                ),
                (
                    "value",
                    fairdm.db.fields.QuantityField(
                        base_units="mW / m^2",
                        help_text="Heat-flow density at a given location after all corrections for instrumental and environmental effects have been applied.",
                        unit_choices=["mW / m^2"],
                        validators=[
                            django.core.validators.MinValueValidator(-1000000),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="heat flow",
                    ),
                ),
                (
                    "uncertainty",
                    fairdm.db.fields.QuantityField(
                        base_units="mW / m^2",
                        blank=True,
                        help_text="Uncertainty (one standard deviation) of the heat-flow value estimated by error propagation from uncertainty in thermal conductivity and temperature gradient, standard deviation from the average of the heat flow intervals or deviation from the linear regression of the Bullard plot.",
                        null=True,
                        unit_choices=["mW / m^2"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000000),
                        ],
                        verbose_name="uncertainty",
                    ),
                ),
                (
                    "corr_HP_flag",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text="Specifies if corrections to the calculated heat flow considers the contribution of the heat production of the overburden to the terrestrial surface heat flow q.",
                        null=True,
                        verbose_name="HP correction flag",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, help_text="General comments on the parent level.", null=True, verbose_name="comment"
                    ),
                ),
                (
                    "is_ghfdb",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether the data entry is part of the Global Heat Flow Database (GHFDB) or not.",
                        verbose_name="GHFDB flag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Heat Flow",
                "verbose_name_plural": "Heat Flow",
                "db_table": "ghfdb_parentheatflow",
                "db_table_comment": "Heat flux at Earth's surface for a given HeatFlowSite. This table roughly correlates to the parent level of the GHFDB schema.",
            },
            bases=("measurement.measurement",),
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ProbeMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "penetration",
                    fairdm.db.fields.DecimalQuantityField(
                        base_units="m",
                        blank=True,
                        decimal_places=2,
                        help_text="Penetration depth of marine heat-flow probe.",
                        max_digits=5,
                        null=True,
                        unit_choices=["m"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="probe penetration",
                    ),
                ),
                (
                    "length",
                    fairdm.db.fields.DecimalQuantityField(
                        base_units="m",
                        blank=True,
                        decimal_places=2,
                        help_text="Length of marine heat-flow probe.",
                        max_digits=5,
                        null=True,
                        unit_choices=["m"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="probe length",
                    ),
                ),
                (
                    "tilt",
                    fairdm.db.fields.DecimalQuantityField(
                        base_units="°",
                        blank=True,
                        decimal_places=2,
                        help_text="Tilt angle of marine heat-flow probe.",
                        max_digits=4,
                        null=True,
                        unit_choices=["°"],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="probe tilt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Probe Metadata",
                "verbose_name_plural": "Probe Metadata",
                "db_table_comment": "Metadata for marine heat flow probe measurements",
            },
        ),
        migrations.RemoveField(
            model_name="surfaceheatflow",
            name="measurement_ptr",
        ),
        migrations.AlterModelOptions(
            name="heatflow",
            options={"ordering": ["pk"], "verbose_name": "Heat Flow", "verbose_name_plural": "Heat Flow"},
        ),
        migrations.RemoveIndex(
            model_name="heatflow",
            name="heat_flow_h_relevan_4eb3f8_idx",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_CONV_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_E_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_HR_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_IS_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_PAL_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_SUR_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_S_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_TOPO_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="corr_T_flag",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="probe_length",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="probe_penetration",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="probe_tilt",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="probe_type",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="relevant_child",
        ),
        migrations.AddField(
            model_name="heatflow",
            name="is_relevant",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether this child measurement was used in calculating the parent heat flow value.",
                verbose_name="is relevant",
            ),
        ),
        migrations.AddField(
            model_name="intervalconductivity",
            name="score",
            field=models.FloatField(
                default=1.1,
                help_text="Score of the thermal conductivity measurement, ranging from 0.0 to 1.0. A score of 1.0 indicates a high-quality measurement, while a score of 0.0 indicates a low-quality measurement.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.1),
                ],
                verbose_name="TC-score",
            ),
        ),
        migrations.AddField(
            model_name="heatflowcorrection",
            name="heat_flow",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="corrections",
                to="heat_flow.heatflow",
                verbose_name="heat flow measurement",
            ),
        ),
        migrations.AddIndex(
            model_name="parentheatflow",
            index=models.Index(fields=["is_ghfdb"], name="ghfdb_paren_is_ghfd_b6ef05_idx"),
        ),
        migrations.AddIndex(
            model_name="parentheatflow",
            index=models.Index(fields=["corr_HP_flag"], name="ghfdb_paren_corr_HP_e744cb_idx"),
        ),
        migrations.AlterField(
            model_name="heatflow",
            name="parent",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="The parent-level heat flow record this measurement contributes to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="heat_flow.parentheatflow",
                verbose_name="parent heat flow",
            ),
        ),
        migrations.AddField(
            model_name="probemetadata",
            name="interval",
            field=auto_prefetch.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="probe_metadata",
                to="heat_flow.heatflowinterval",
                verbose_name="heat flow measurement",
            ),
        ),
        migrations.AddField(
            model_name="probemetadata",
            name="probe_type",
            field=research_vocabs.fields.ConceptManyToManyField(
                blank=True,
                help_text="Type of heat-flow probe used for measurement.",
                related_name="+",
                to="research_vocabs.concept",
                verbose_name="probe type",
                vocabulary=heat_flow.vocabularies.ProbeType,
            ),
        ),
        migrations.AddIndex(
            model_name="heatflowcorrection",
            index=models.Index(fields=["correction_type"], name="heat_flow_h_correct_486af7_idx"),
        ),
        migrations.AddIndex(
            model_name="heatflowcorrection",
            index=models.Index(fields=["status"], name="heat_flow_h_status_e2e67d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="heatflowcorrection",
            unique_together={("heat_flow", "correction_type")},
        ),
        migrations.DeleteModel(
            name="SurfaceHeatFlow",
        ),
    ]
