# Generated by Django 5.2.5 on 2026-04-09 19:37

import auto_prefetch
import django.core.validators
import django.db.models.deletion
import fairdm.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heat_flow", "0005_ghfdbrelease_heatflowcorrection_parentheatflow_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GHFDBRelease",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="IGSN",
        ),
        migrations.AlterField(
            model_name="heatflow",
            name="thermal_conductivity",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="Thermal conductivity value used for heat-flow calculation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="heat_flow_children",
                to="heat_flow.intervalconductivity",
                verbose_name="thermal conductivity",
            ),
        ),
        migrations.AlterField(
            model_name="heatflow",
            name="thermal_gradient",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="Temperature gradient value used for heat-flow calculation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="heat_flow_children",
                to="heat_flow.thermalgradient",
                verbose_name="temperature gradient",
            ),
        ),
        migrations.AlterField(
            model_name="intervalconductivity",
            name="value",
            field=fairdm.db.fields.DecimalQuantityField(
                base_units="W/mK",
                decimal_places=2,
                help_text="Mean conductivity in vertical direction representative for the interval of heat-flow determination. In best case, the value reflects the true in-situ conditions for the corresponding heat-flow interval.",
                max_digits=4,
                unit_choices=["W/mK"],
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Mean thermal conductivity",
            ),
        ),
        migrations.AlterField(
            model_name="thermalgradient",
            name="value",
            field=fairdm.db.fields.DecimalQuantityField(
                base_units="K/km",
                db_comment="Calculated or inferred temperature gradient.",
                decimal_places=2,
                help_text="Mean thermal gradient measured over a given length interval.",
                max_digits=7,
                unit_choices=["K/km"],
                validators=[
                    django.core.validators.MinValueValidator(-100000),
                    django.core.validators.MaxValueValidator(100000),
                ],
                verbose_name="thermal gradient",
            ),
        ),
    ]
