# Generated by Django 5.2.5 on 2026-04-09 19:53

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("heat_flow", "0006_ghfdb_data_model_cleanup"),
        ("sample", "0005_alter_sample_options_alter_samplerelation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="heatflowinterval",
            name="sample",
            field=auto_prefetch.ForeignKey(
                blank=True,
                help_text="The heat flow site this depth interval belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intervals",
                to="sample.sample",
                verbose_name="parent site",
            ),
        ),
    ]
