# Generated by Django 5.2.5 on 2026-04-10 06:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("heat_flow", "0007_add_interval_site_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parentheatflow",
            options={
                "verbose_name": "Parent Heat Flow",
                "verbose_name_plural": "Parent Heat Flow",
            },
        ),
    ]
