# Generated by Django 5.2.5 on 2026-04-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heat_flow", "0008_update_parent_heat_flow_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="heatflow",
            name="local_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="GHFDB spreadsheet ID column — used as the stable key for import upsert",
                max_length=255,
                null=True,
            ),
        ),
    ]
