# Generated by Django 5.2.5 on 2026-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heat_flow", "0009_heatflow_local_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="parentheatflow",
            name="local_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="GHFDB spreadsheet ID_parent column — used as the stable key for import upsert",
                max_length=255,
                null=True,
            ),
        ),
    ]
