# Generated by Django 5.2.5 on 2026-04-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heat_flow", "0010_add_local_id_fields"),
        ("measurement", "0007_alter_measurementdate_type_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="parentheatflow",
            name="ghfdb_paren_is_ghfd_b6ef05_idx",
        ),
        migrations.RemoveField(
            model_name="heatflow",
            name="local_id",
        ),
        migrations.RemoveField(
            model_name="parentheatflow",
            name="is_ghfdb",
        ),
        migrations.RemoveField(
            model_name="parentheatflow",
            name="local_id",
        ),
        migrations.AddField(
            model_name="heatflow",
            name="ghfdb_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="The original unique identifier for this record in the GHFDB schema, used for traceability.",
                null=True,
                verbose_name="ID Child",
            ),
        ),
        migrations.AddField(
            model_name="heatflow",
            name="quality",
            field=models.CharField(
                blank=True,
                help_text="Overall quality assessment of the heat-flow value, based on a combination of U-score and M-score, as well as expert judgment on the reliability of the data.",
                max_length=13,
                null=True,
                verbose_name="quality score",
            ),
        ),
        migrations.AddField(
            model_name="parentheatflow",
            name="ghfdb_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="The original unique identifier for this record in the GHFDB schema, used for traceability.",
                null=True,
                verbose_name="ID Parent",
            ),
        ),
        migrations.AddField(
            model_name="parentheatflow",
            name="quality",
            field=models.CharField(
                blank=True,
                help_text="Overall quality assessment of the heat-flow value, based on a combination of U-score and M-score, as well as expert judgment on the reliability of the data.",
                max_length=13,
                null=True,
                verbose_name="quality score",
            ),
        ),
        migrations.AddIndex(
            model_name="parentheatflow",
            index=models.Index(fields=["ghfdb_id"], name="ghfdb_paren_ghfdb_i_6b75a3_idx"),
        ),
    ]
