# Generated by Django 5.2.17 on 2026-09-15 14:11

import django.core.validators
import fairdm.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heat_flow', '0012_interval_site_and_parent_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heatflow',
            old_name='water_temperature',
            new_name='surface_temperature',
        ),
        migrations.AlterField(
            model_name='heatflow',
            name='surface_temperature',
            field=fairdm.db.fields.QuantityField(base_units='°C', blank=True, help_text='Temperature at the upper boundary of the heat-flow determination interval: seafloor or bottom-water temperature for a marine measurement, ground-surface or mudline temperature for a continental one. e.g. PT 100 or Mudline temperature for ocean drilling data.', null=True, unit_choices=['°C', 'K'], validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(1000)], verbose_name='surface temperature'),
        ),
        migrations.AddField(
            model_name='thermalgradient',
            name='temperature_bottom',
            field=fairdm.db.fields.QuantityField(base_units='°C', blank=True, help_text='Mean absolute temperature at the bottom of the heat-flow determination interval, used to calculate the temperature gradient.', null=True, unit_choices=['°C', 'K'], validators=[django.core.validators.MinValueValidator(-99999.99), django.core.validators.MaxValueValidator(99999.99)], verbose_name='temperature (bottom)'),
        ),
        migrations.AddField(
            model_name='thermalgradient',
            name='temperature_bottom_uncertainty',
            field=fairdm.db.fields.QuantityField(base_units='°C', blank=True, help_text='Uncertainty (1 sigma) of the mean absolute temperature at the bottom of the heat-flow determination interval.', null=True, unit_choices=['°C', 'K'], validators=[django.core.validators.MinValueValidator(-99999.99), django.core.validators.MaxValueValidator(99999.99)], verbose_name='temperature uncertainty (bottom)'),
        ),
        migrations.AddField(
            model_name='thermalgradient',
            name='temperature_top',
            field=fairdm.db.fields.QuantityField(base_units='°C', blank=True, help_text='Mean absolute temperature at the top of the heat-flow determination interval, used to calculate the temperature gradient.', null=True, unit_choices=['°C', 'K'], validators=[django.core.validators.MinValueValidator(-99999.99), django.core.validators.MaxValueValidator(99999.99)], verbose_name='temperature (top)'),
        ),
        migrations.AddField(
            model_name='thermalgradient',
            name='temperature_top_uncertainty',
            field=fairdm.db.fields.QuantityField(base_units='°C', blank=True, help_text='Uncertainty (1 sigma) of the mean absolute temperature at the top of the heat-flow determination interval.', null=True, unit_choices=['°C', 'K'], validators=[django.core.validators.MinValueValidator(-99999.99), django.core.validators.MaxValueValidator(99999.99)], verbose_name='temperature uncertainty (top)'),
        ),
    ]
