# Generated by Django 5.2.17 on 2026-09-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_flow', '0013_rename_water_temperature_and_add_thermalgradient_temps'),
        ('measurement', '0012_alter_measurement_name'),
        ('research_vocabs', '0002_alter_concept_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatflow',
            name='TC_score',
            field=models.FloatField(blank=True, editable=False, help_text="The child's thermal-conductivity score after its own corrections are applied, from 0.1 to 1.2. It equals the TC-score the Heat Flow Quality Analysis Toolbox gives the same row. Empty means not determined. Calculated by the portal.", null=True, verbose_name='TC-score (corrected)'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='TC_score_missing',
            field=models.BooleanField(default=False, editable=False, help_text='True when an input the corrected TC-score needed was empty. Calculated by the portal.', verbose_name='TC-score reached with missing information'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='T_score',
            field=models.FloatField(blank=True, editable=False, help_text="The child's temperature-gradient score after its own corrections are applied, from 0.1 to 1.2. It equals the T-score the Heat Flow Quality Analysis Toolbox gives the same row. Empty means not determined. Calculated by the portal.", null=True, verbose_name='T-score (corrected)'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='T_score_missing',
            field=models.BooleanField(default=False, editable=False, help_text='True when an input the corrected T-score needed was empty. Calculated by the portal.', verbose_name='T-score reached with missing information'),
        ),
        migrations.AddField(
            model_name='heatflow',
            name='quality_scheme',
            field=models.CharField(blank=True, default='', editable=False, help_text='The revision of the quality scheme that calculated the stored scores, for example hfqa_tool 0.2. Empty until the scores have been calculated.', max_length=32, verbose_name='scheme revision'),
        ),
        migrations.AddField(
            model_name='intervalconductivity',
            name='quality_scheme',
            field=models.CharField(blank=True, default='', editable=False, help_text='The revision of the quality scheme that calculated the stored score, for example hfqa_tool 0.2. Empty until the score has been calculated.', max_length=32, verbose_name='scheme revision'),
        ),
        migrations.AddField(
            model_name='intervalconductivity',
            name='score_missing',
            field=models.BooleanField(default=False, editable=False, help_text="True when an input the TC-score needed was empty, so the score takes the criterion's largest penalty without the information being known.", verbose_name='TC-score reached with missing information'),
        ),
        migrations.AddField(
            model_name='thermalgradient',
            name='quality_scheme',
            field=models.CharField(blank=True, default='', editable=False, help_text='The revision of the quality scheme that calculated the stored score, for example hfqa_tool 0.2. Empty until the score has been calculated.', max_length=32, verbose_name='scheme revision'),
        ),
        migrations.AddField(
            model_name='thermalgradient',
            name='score_missing',
            field=models.BooleanField(default=False, editable=False, help_text="True when an input the T-score needed was empty, so the score takes the criterion's largest penalty without the information being known.", verbose_name='T-score reached with missing information'),
        ),
        migrations.AlterField(
            model_name='heatflow',
            name='M_score',
            field=models.CharField(choices=[('M1', 'Excellent'), ('M2', 'Good'), ('M3', 'Acceptable'), ('M4', 'Poor'), ('M1x', 'Excellent, with missing information'), ('M2x', 'Good, with missing information'), ('M3x', 'Acceptable, with missing information'), ('M4x', 'Poor, with missing information'), ('Mx', 'Not determined / missing data')], default='Mx', editable=False, help_text='Methodological quality of the heat-flow value, graded from the product of the corrected T-score and TC-score (Fuchs et al. 2023; Dergunova et al. 2026). M1 = Excellent, M2 = Good, M3 = Ok, M4 = Poor, Mx = not determined / missing data. A trailing x marks a grade reached with missing information. Calculated by the portal.', max_length=3, verbose_name='M-score'),
        ),
        migrations.AlterField(
            model_name='heatflow',
            name='U_score',
            field=models.CharField(choices=[('U1', 'Excellent'), ('U2', 'Good'), ('U3', 'Acceptable'), ('U4', 'Poor'), ('Ux', 'Not determined / missing data')], default='Ux', editable=False, help_text='Numerical uncertainty of the heat-flow value, graded from the uncertainty as a percentage of the value (Fuchs et al. 2023; Dergunova et al. 2026). U1 = Excellent, U2 = Good, U3 = Ok, U4 = Poor, Ux = not determined / missing data. Calculated by the portal.', max_length=2, verbose_name='U-score'),
        ),
        migrations.AlterField(
            model_name='heatflow',
            name='quality',
            field=models.CharField(blank=True, editable=False, help_text='The quality code: the U-score, the M-score and the seven perturbation flags (S E T P V C R), joined by dots, for example U2.M3x.-e-PX--. Calculated by the portal.', max_length=14, null=True, verbose_name='quality score'),
        ),
        migrations.AlterField(
            model_name='intervalconductivity',
            name='score',
            field=models.FloatField(blank=True, editable=False, help_text="The conductivity's own score under the toolbox V0.2 scheme (Dergunova et al. 2026), from 0.1 to 1.2. It is calculated from the conductivity, its interval and its site, and reads no child's corrections. Empty means not determined, because the site's exploration method selects neither rule set.", null=True, verbose_name='TC-score'),
        ),
        migrations.AlterField(
            model_name='thermalgradient',
            name='score',
            field=models.FloatField(blank=True, editable=False, help_text="The gradient's own score under the toolbox V0.2 scheme (Dergunova et al. 2026), from 0.1 to 1.2. It is calculated from the gradient, its interval and its site, and reads no child's corrections. Empty means not determined, because the site's exploration method selects neither rule set.", null=True, verbose_name='T-score'),
        ),
        migrations.AddIndex(
            model_name='heatflow',
            index=models.Index(fields=['T_score'], name='heat_flow_h_T_score_f3e363_idx'),
        ),
        migrations.AddIndex(
            model_name='heatflow',
            index=models.Index(fields=['TC_score'], name='heat_flow_h_TC_scor_b9f8cf_idx'),
        ),
        migrations.AddIndex(
            model_name='intervalconductivity',
            index=models.Index(fields=['score'], name='heat_flow_i_score_d39777_idx'),
        ),
    ]
