# Generated by Django 5.2.17 on 2026-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heat_flow', '0013_rename_water_temperature_and_add_thermalgradient_temps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatflow',
            name='M_score',
            field=models.CharField(choices=[('M1', 'Excellent'), ('M2', 'Good'), ('M3', 'Acceptable'), ('M4', 'Poor'), ('M1x', 'Excellent, with missing information'), ('M2x', 'Good, with missing information'), ('M3x', 'Acceptable, with missing information'), ('M4x', 'Poor, with missing information'), ('Mx', 'Not determined / missing data')], default='Mx', help_text='Methodological quality of the heat-flow value, as defined in Fuchs et al. (2023). M1 = Excellent, M2 = Good, M3 = Ok, M4 = Poor, Mx = not determined / missing data.', max_length=3, verbose_name='M-score'),
        ),
    ]
