# Generated by Django 2.2.24 on 2021-10-21 23:45

from django.db import migrations, models
import uploads.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_type', models.IntegerField(choices=[(0, 'Heat Flow'), (1, 'Thermal Gradient'), (2, 'Temperature'), (3, 'Thermal Conductivity'), (4, 'heat production')], default=0)),
                ('data', models.FileField(upload_to=uploads.models.file_storage_path)),
                ('bibtex', models.TextField(blank=True, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('imported', models.BooleanField(default=False)),
                ('date_imported', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Upload',
                'ordering': ['-date_uploaded'],
            },
        ),
    ]
